add: アームを上げるコマンドと下げるコマンドを追加した
KatLab-MiyazakiUniv/etrobocon2022 pull request #103
Opened 2022-08-27 12:29 UTC by KakinokiKanta

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- アームを上げるコマンドの追加
- アームを下げるコマンドの追加
- 全カラーブロックの完成
- 不良ブロックの完成

# 動作テスト
- 実機においてアームを上げるコマンドと下げるコマンドが動作することを確認

## 添付資料

https://user-images.githubusercontent.com/105735727/187030270-0eb6bdd5-af4f-4898-8a94-67a582ae1c7a.MOV

2022-08-27 15:31 UTC, miyashita64 requested changes
早めのプルリクお疲れ様です。

まだ、作業中だったかもしれませんが、気になったところにコメントしたので対応お願いします。
ArmKeeperとArmRisingにもauthorを追記してください。

2022-08-28 05:19 UTC, KakinokiKanta commented on datafiles/ToEndPointRight.csv
> +DT,120,70,0,左に90度ピボットターン（旋回）
この変更については、動作確認をしていたときに、ピボットターンの向きが逆だったため、勝手に変更しちゃいました。

2022-08-30 10:40 UTC, miyashita64 requested changes
動作はいいと思います。
細かい修正をお願いします。

2022-08-30 10:40 UTC, miyashita64 commented on module/Motion/ArmRising.h
> + * @file ArmFalling.h
変更漏れ

2022-08-30 10:40 UTC, miyashita64 commented on test/MotionParserTest.cpp
ArmFallingについても書いてほしいです。

2022-08-30 10:40 UTC, miyashita64 commented on test/test_data/CommandParserTestData.csv
> +AR,10,100,タスクスリープ
```suggestion
AR,10,100,アームを上げる
```

2022-08-31 18:24 UTC, mutotaka0426 requested changes
いくつか指摘してるので対応お願いします

あとArmRisingとArmFallingのテストが欲しいです

2022-08-31 18:24 UTC, mutotaka0426 commented on datafiles/ArmRising.csv
> +AF,60,25,アーム下降
このファイルはプッシュする必要ない？

2022-08-31 18:24 UTC, mutotaka0426 commented on module/Motion/ArmFalling.h
> +   */
引数についても書いてほしい
```suggestion
  /**
   * コンストラクタ
   * @param _angle アームを下げる角度 0~
   * @param _pwm PWM値 0~100
   */
```
値の範囲はあってるかわかんないから，正しいのにして

2022-08-31 18:24 UTC, mutotaka0426 commented on module/Motion/ArmFalling.h
> +   * @brief 実行する
他のコマンドに合わせるとこうかな？
```suggestion
   * @brief アームを下げる
```

2022-08-31 18:24 UTC, mutotaka0426 commented on module/Motion/ArmRising.h
> +   */
ここも
```suggestion
  /**
   * コンストラクタ
   * @param _angle アームを上げる角度 0~
   * @param _pwm PWM値 0~100
   */
```

2022-08-31 18:24 UTC, mutotaka0426 commented on module/Motion/ArmRising.h
> +   * @brief 実行する
ここも
```suggestion
   * @brief アームを上げる
```

2022-08-31 18:24 UTC, mutotaka0426 commented on module/Motion/ArmFalling.cpp
> +  int initCount = measurer.getArmMotorCount();
worning処理を追加してほしい
他のコマンドを参考にしてくれれば分かると思う

とりあえずangleが0以下のときと，pwmが0以下のときにworningを出してreturnしてくれればいいかな？

angleは何度以上指定されたら困るとかってある？あるならそれも

2022-08-31 18:24 UTC, mutotaka0426 commented on module/Motion/ArmRising.cpp
> +  int initCount = measurer.getArmMotorCount();
こっちもworning処理の追加よろしく

2022-09-01 12:28 UTC, mutotaka0426 requested changes
小さな修正を追加でお願いします

あとworningのテストが欲しいかも
pwmに100指定したときにちゃんとwarningを出して，かつ，走ってるかとか
その時はerrorの計算の中のpwmは↓のように60にしてね
```
double error = 60 * 0.05;  // 許容誤差[deg]
```

2022-09-01 12:28 UTC, mutotaka0426 commented on module/Motion/ArmFalling.h
> +  int pwm;    // PWM値 0~100
```suggestion
  int angle;  // 回転角度(deg) 0~60
  int pwm;    // PWM値 0~40
```

2022-09-01 12:28 UTC, mutotaka0426 commented on module/Motion/ArmRising.h
> +  int pwm;    // PWM値 0~100
```suggestion
  int angle;  // 回転角度(deg) 0~60
  int pwm;    // PWM値 0~40
```

2022-09-01 12:28 UTC, mutotaka0426 commented on test/ArmFallingTest.cpp
> +    EXPECT_GE(expected + error, ArmMotorCount);
```suggestion
    int actual = abs(measurer.getArmMotorCount() - initialArmMotorCount);

    EXPECT_LE(expected, actual);
    EXPECT_GE(expected + actual);
```

2022-09-01 12:28 UTC, mutotaka0426 commented on test/ArmFallingTest.cpp
> +    string output = testing::internal::GetCapturedStdout();  // キャプチャ終了
標準出力キャプチャする必要ある？
この値だったworning出すわけじゃないから，むしろ出して何も出てないこと確認できた方がよくない？

warningが出ることの確認をする場合はキャプチャした方がいいね
ていうかwarningのテストもしてほしいかも

2022-09-01 12:28 UTC, mutotaka0426 commented on test/ArmRisingTest.cpp
> +    EXPECT_GE(expected + error, ArmMotorCount);
```suggestion
    int actual = abs(measurer.getArmMotorCount() - initialArmMotorCount);

    EXPECT_LE(expected, actual);
    EXPECT_GE(expected + error, actual);
```

2022-09-01 12:28 UTC, mutotaka0426 commented on test/ArmRisingTest.cpp
> +    string output = testing::internal::GetCapturedStdout();  // キャプチャ終了
ここも

2022-09-02 06:22 UTC, miyashita64 approved these changes
お疲れ様です！
![LGTM](https://image.lgtmoon.dev/179787)

2022-09-02 08:38 UTC, mutotaka0426 approved these changes
テストも完璧だと思う！
お疲れ様！
![LGTM](https://image.lgtmoon.dev/179819)

2022-09-02 09:12 UTC, kodama0720 approved these changes
LGTM!

2022-09-02 10:25 UTC, merged