close #100 カメラシステムに競技開始を合図する
KatLab-MiyazakiUniv/etrobocon2022 pull request #108
Opened 2022-08-30 08:00 UTC by miyashita64

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- サーバ起動するシェルファイルを作成
- メッセージ用のテキストファイルを作成
- ETrobocon2022.cppにシェルを呼び出す処理を追加

# 動作テスト

## 実験方法
カメラシステムへ競技開始合図を送り、カメラシステムがそれを受信していることを確認する。

## 実験データ

## 実験結果
競技開始をカメラシステムに合図できた。

## 参考資料
[Qitta ShellScriptのみを使って今Webサーバを作るとしたら](https://qiita.com/wf-yamaday/items/f890f3523eeacbe71153)

2022-08-31 11:26 UTC, kodama0720 reviewed
見た感じ良いと思います
serverじゃなくてserveなのはわざと？

2022-08-31 11:33 UTC, miyashita64 commented
> serverじゃなくてserveなのはわざと？

シェルファイルは名前が動詞なことが多い気がしたので、serveにしています。

2022-08-31 17:56 UTC, mutotaka0426 requested changes
大した指摘はないけど対応お願いします

2022-08-31 17:56 UTC, mutotaka0426 commented on module/EtRobocon2022.cpp
> +  // 開始合図を送る
```suggestion
  // カメラシステムに開始合図を送る
```

2022-08-31 17:56 UTC, mutotaka0426 commented on scripts/message.txt
> +Start
このファイル追跡する必要ないんじゃない？

2022-08-31 17:56 UTC, mutotaka0426 commented on scripts/start.sh
> +echo -n Start > message.txt
`serve.sh`と同様に書いた方がいい
```suggestion
echo -n "Start" > message.txt
```

2022-08-31 17:56 UTC, mutotaka0426 commented on scripts/message.txt
> +Start
ていうか終わったら不要なファイルはシェル消すべき？serve.shの最後とかで

2022-09-01 02:27 UTC, sugaken0528 approved these changes
LGTM!!

2022-09-01 03:21 UTC, KakinokiKanta approved these changes
LGTM!

2022-09-01 04:34 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/179605)

2022-09-01 04:42 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-09-01 05:50 UTC, merged