update:#33 決め打ち動作コマンドの追加
KatLab-MiyazakiUniv/etrobocon2022 pull request #121
Opened 2022-09-14 13:12 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
ボーナスブロック設置動作の調整で一番精度の高いNorthのコマンドファイルを決め打ちコマンドファイルとして追加
精度の詳細は以下のURLから
[https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/pull/43](url)

2022-09-14 16:06 UTC, mutotaka0426 requested changes
ファイル名を変えてほしいのと，ボーナスブロック設置のコマンドファイルを読み込んで実行する処理も，GameArea.cppとGameArea.hに追加してほしい

ついでに，プルリクのリンクの貼り方間違ってるよ
リンク先がおかしい

2022-09-14 16:06 UTC, mutotaka0426 commented on datafiles/LeftBonusCarry.csv
> +DS,50,70,[左コースボーナスブロック運搬決め打ちコマンド(北)]調整直進
他のコマンドファイルは名前の末尾に`Left`or`Right`がついてるから，これらのファイルも合わせたい
かつ，カメラシステム側に置いているファイルとも合わせたいから，`CarryBonusLeft.csv`とかにして，カメラシステム側は`EastBonusLeft.csv`とか？

2022-09-14 22:40 UTC, mutotaka0426 requested changes
小さい修正だけ
よろしくお願いします

2022-09-14 22:40 UTC, mutotaka0426 commented on module/GameArea.cpp
> +    eMotion->run();
carryのcじゃないかな
```suggestion
  for(const auto& cMotion : carryBonusMotions) {
    cMotion->logRunning();
    cMotion->run();
```

2022-09-14 22:40 UTC, mutotaka0426 commented on module/GameArea.cpp
> +  // ボーナスブロック運搬までの動作インスタンスのリストを生成する
まで？
```suggestion
  // ボーナスブロック運搬のコマンドファイルを読み込む
  const char* carryBonusPath = isLeftCourse ? carryBonusLeft : carryBonusRight;
  // ボーナスブロック運搬の動作インスタンスのリストを生成する
```

2022-09-14 22:40 UTC, mutotaka0426 commented on module/GameArea.h
> +  // ボーナスブロック運搬までのコマンドファイルのパス
ここも？
```suggestion
  // ボーナスブロック運搬のコマンドファイルのパス
```

2022-09-15 07:17 UTC, kawanoichi commented on module/GameArea.cpp
> +  // ボーナスブロック運搬までの動作インスタンスのリストを生成する
復帰動作のことを書くの忘れていたので
```// ボーナスブロック運搬、復帰までのコマンドファイル```
にしました。これでも大丈夫ですか？
```// ボーナスブロック運搬、復帰のコマンドファイル```
の方がいいですか？

2022-09-15 07:20 UTC, mutotaka0426 commented on module/GameArea.cpp
> +  // ボーナスブロック運搬までの動作インスタンスのリストを生成する
復帰込みでボーナスブロック運搬じゃない？
復帰ってあくまで構成要素の一つだから書かなくていいのでは？

2022-09-15 07:27 UTC, Takahiro55555 approved these changes
LGTM

2022-09-15 07:45 UTC, mutotaka0426 approved these changes
お疲れ様です
![LGTM](https://image.lgtmoon.dev/181397)

2022-09-15 10:00 UTC, sap2368 approved these changes
LGTM

2022-09-15 10:05 UTC, merged