close #135 ログをファイルに保存する
KatLab-MiyazakiUniv/etrobocon2022 pull request #138
Opened 2022-10-14 20:24 UTC by mutotaka0426

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- Loggerインスタンスが出力するログを，logsに保持するように拡張
- 競技終了時にlogsをファイル出力するように拡張
- 強制終了時にもlogsをファイル出力する

# 動作テスト
競技終了時及び強制終了時にログファイルが出力されていることを確認．

## 問題点
CTRL+cをしても稀に強制終了ができない時がある．
しかしCTRL+cをした時点でファイル出力はできており，CTRL+zで終了すれば問題なく終了できる．

2022-10-16 06:10 UTC, miyashita64 approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/81901)

2022-10-16 11:34 UTC, kodama0720 approved these changes
LGTM!

2022-10-17 02:07 UTC, kawanoichi approved these changes
![84724](https://user-images.githubusercontent.com/96767490/196073997-67d76c5b-bef7-4789-9818-9b051e38d8f2.png)

2022-10-17 19:59 UTC, sugaken0528 requested changes
コードは見た感じ大丈夫だと思います
動作テストは出力例もお願いします

2022-10-18 04:35 UTC, sugaken0528 approved these changes
LGTM

2022-10-18 04:35 UTC, merged