close #4 Pidクラスを追加する
KatLab-MiyazakiUniv/etrobocon2022 pull request #14
Opened 2022-06-09 07:17 UTC by Cryogonal

# 完了条件
- [x] 完了条件を満たしている
- [x] gtestが通ることを確認している

# 変更点
- Pid.cpp, Pid.hを追加
- PidTest.cppを追加

2022-06-12 13:40 UTC, Takahiro55555 requested changes
全体的に良いコードだと思います。
ただし、一点だけ、コメントの通り`preDeviation`という変数名は修正したほうが良いと考えます。
お手数ですが、よろしくお願いいたします。

2022-06-12 13:40 UTC, Takahiro55555 commented on module/Motion/Pid.cpp
> +  preDeviation = presentDeviation;
少し、気になった点として、`pre`と略してしまうと`present`と`previous`どちらかわかりづらいので、修正したほうが良いと思います。

```suggestion
  previousDeviation = presentDeviation;
```
or
```suggestion
  prevDeviation = presentDeviation;
```

2022-06-14 02:25 UTC, mutotaka0426 commented on module/Motion/Pid.cpp
> +  preDeviation = presentDeviation;
そもそもpresentを使わない方がいい気がする
previousを使うとなると特に紛らわしいから，nowとかcurrentにするべきか？

2022-06-14 05:38 UTC, mutotaka0426 commented on module/Motion/Pid.cpp
> +  preDeviation = presentDeviation;
名前を修正する場合は，テストコードの変数名も変えるのを忘れずに

2022-06-14 05:49 UTC, mutotaka0426 requested changes
小さいところだけ指摘しているけど，大部分はok
あとは上田くんの指摘に補足した分を修正してくれれば大丈夫だと思います

2022-06-14 05:49 UTC, mutotaka0426 commented on test/PidTest.cpp
> +    static const double DELTA = 0.01;
staticは何で付けてる？
ここだけで定数だし，スコープは極力狭くしないと名前の衝突が起きると思う

あと，基本的にC++ではconstじゃなくてconstexprを使った方がいい[（参考資料）](https://qiita.com/saltheads/items/dd65935878a0901fe9e7)
```suggestion
    constexpr double DELTA = 0.01;
```

2022-06-14 11:14 UTC, kodama0720 requested changes

2022-06-14 11:14 UTC, kodama0720 commented on test/PidTest.cpp
> +  TEST(PidTest, caluculatePid)
caluculate → calculate だと思う
以降も同じ

2022-06-14 11:14 UTC, kodama0720 commented on test/PidTest.cpp
> +  TEST(PidTest, caluculatePid_cahgeDelta)
cahge → change?

2022-06-14 11:18 UTC, kodama0720 commented on test/PidTest.cpp
> +  TEST(PidTest, caluculatePid_zero)
ここも
それとテストケース名をキャメルケースかスネークケースかでそろえた方がいい
とりあえずキャメルケースに揃えようかと思います（例：calculatePidZero）

2022-06-14 21:00 UTC, sugaken0528 reviewed
全体的に特に問題は無いと思う。指摘されている箇所の修正をお願いします。

2022-06-15 23:22 UTC, miyashita64 approved these changes
LGTM!

2022-06-16 01:29 UTC, kodama0720 commented on module/Motion/Pid.cpp
> +  preDeviation = presentDeviation;
今更申し訳ありませんが、nowよりcurrentの方がよさそうです。
nowだと現在時刻とかの意味になる気がします。
[参考](https://hexadrive.jp/hexablog/diary/23671/)

2022-06-16 03:39 UTC, kodama0720 commented on module/Motion/Pid.h
> +  double calculatePid(double presentValue, double delta = 0.01);
ここも

2022-06-16 06:22 UTC, kodama0720 approved these changes
LGTM!

2022-06-16 06:47 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/139280)

2022-06-16 06:57 UTC, Takahiro55555 approved these changes
LGTM!!!

お疲れ様でした。

2022-06-16 07:00 UTC, merged