add: 角度補正回頭の追加
KatLab-MiyazakiUniv/etrobocon2022 pull request #148
Opened 2022-10-28 06:52 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
変更点として以下の通りです
- 角度補正回頭をする CorrectingRotation クラスの追加
- MotionPerser クラスに角度補正回頭をするXRコマンドの追加
- scripts/ 下のファイルの命名規則をスネークケースに変更

# 動作テスト
補正(回頭)すべき方向があっているかを検証しました。
補正角度の大きさは考慮していません。
回頭補正コマンドのパラメータは以下の通りです。
```
XR,目標角度,PWM
```
## パターン①
- コマンド ```XR,45,60```
- リアカメラから取得した角度　```-63.93```
![image](https://user-images.githubusercontent.com/96767490/198518936-4eb17b70-8811-42e1-9fff-b3408cefbaaf.png)

## パターン②
コマンド ```XR,45,60```
リアカメラから取得した角度　```69.16```
![image](https://user-images.githubusercontent.com/96767490/198519037-9bf2650e-7e12-49e5-827e-994cf0b905c5.png)

## パターン③
コマンド ```XR,45,60```
リアカメラから取得した角度　```30.09```
![image](https://user-images.githubusercontent.com/96767490/198519058-9d59fd72-e305-46be-ab80-b2c20d09c553.png)

## パターン④
コマンド ```XR,45,60```
リアカメラから取得した角度　```-30.08```
![image](https://user-images.githubusercontent.com/96767490/198519083-9e3b1e47-9582-40bb-950a-65754c5a1bc7.png)

## パターン⑤
コマンド ```XR,0,60```
リアカメラから取得した角度　```-74.45```
![image](https://user-images.githubusercontent.com/96767490/198519127-beae24e4-484d-4c96-baf4-c34fb3cf0963.png)

## パターン⑥
コマンド ```XR,0,60```
リアカメラから取得した角度　```77.93```
![image](https://user-images.githubusercontent.com/96767490/198519155-507b268f-1264-4d47-b160-2213235ab25a.png)

## パターン⑦
コマンド ```XR,0,60```
リアカメラから取得した角度　```12.08```
![image](https://user-images.githubusercontent.com/96767490/198519189-4d7a92dd-bbfe-4216-beb5-85fc63ef4df7.png)

## パターン⑧
コマンド ```XR,0,60```
リアカメラから取得した角度　```-5.15```
![image](https://user-images.githubusercontent.com/96767490/198519233-4ad679f1-2ef2-46aa-92ba-a7779a8de316.png)

## パターン⑨ ボーナスブロック取得時
コマンド ```XR,64,60```
リアカメラから取得した角度　```-45.03```
![image](https://user-images.githubusercontent.com/96767490/198519264-49a16b5a-ba65-441d-b4c9-0e04c98fe706.png)

## パターン⑩ ボーナスブロック取得時
コマンド ```XR,64,60```
リアカメラから取得した角度　```83.07```
![image](https://user-images.githubusercontent.com/96767490/198519291-c130d300-8bb0-4d9c-bbbe-98708ae3d397.png)

2022-10-28 07:48 UTC, Takahiro55555 commented
現在、Python側では黒線を一つも認識できなかった場合、`None`を返すようにしてるんだけど何も出力せずに異常終了する方が都合が良かったりする？

2022-10-28 14:00 UTC, mutotaka0426 commented
> 現在、Python側では黒線を一つも認識できなかった場合、`None`を返すようにしてるんだけど何も出力せずに異常終了する方が都合が良かったりする？

atofで変換する時，数値じゃなかったら0を返すはずだから，問題が起きるね
こっち側でNoneが返ってきたときの処理をいれた方がいいかも
その方がworningの処理とか書きやすいし
追加しとくわ

2022-10-29 15:57 UTC, miyashita64 requested changes
内容はいいと思います。
細かい修正をお願いします。

2022-10-29 15:57 UTC, miyashita64 commented on module/common/StringOperator.cpp
> + * @brief 文字列を操作するstatic関数をを持つクラス
```suggestion
 * @brief 文字列を操作するstatic関数を持つクラス
```

2022-10-29 15:57 UTC, miyashita64 commented on test/StringOperatorTest.cpp
> + * @file   StringOperator.cpp
```suggestion
 * @file   StringOperatorTest.cpp
```

2022-11-01 04:39 UTC, miyashita64 approved these changes
LGTM!!

2022-11-01 04:55 UTC, KakinokiKanta approved these changes
LGTM!!

2022-11-01 07:22 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-11-01 07:27 UTC, merged