黒抽出モジュールの追加
KatLab-MiyazakiUniv/etrobocon2022 pull request #150
Opened 2022-10-29 03:13 UTC by kodama0720

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- etrobocon2022/rear_camera_py/rear_camera/に黒抽出を行うモジュールblack_extractor.pyを追加した

# 動作テスト
## 実験方法
- リアカメラ画像から黒線の抽出を行った

## 実験結果
- 目で見ても黒く見える部分のみを検出できた
- 実行時間は0.11~0.12秒程度
## 添付資料

![rear_camera1](https://user-images.githubusercontent.com/83354922/198798051-2e840592-fccd-4a55-a1d8-3e4e6f14efd5.png)

![binary_rear_camera1](https://user-images.githubusercontent.com/83354922/198797947-ec5f5d66-2761-493c-be8b-48774b8bc5eb.png)

2022-10-29 07:01 UTC, Takahiro55555 requested changes

2022-10-29 07:01 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/black_extractor.py
> +    result = black_extractor.extract_black(rear_camera_img)
`@staticmethod`を採用した場合、多分以下のような感じで動くと思います(動作未確認)...
```suggestion
    # 2値変換
    result = BlackExtractor.extract_black(rear_camera_img)
```

2022-10-29 15:38 UTC, miyashita64 requested changes

2022-10-29 15:38 UTC, miyashita64 commented on rear_camera_py/rear_camera/black_extractor.py
> +        upper = np.array([180, 245, 255])
```suggestion
        MIN_WHITE_VALUE = 80             # 白と識別するための最低輝度
        MAX_WHITE_SATURATION=245 # 白と識別する最高彩度
        lower_hsv = np.array([0, 0, MIN_WHITE_VALUE])
        upper_hsv = np.array([180, MAX_WHITE_SATURATION, 255])
```
上記のような形(認識を間違えていたらすみません)かコメントで、2値判定の基準をわかりやすくしてほしいです。
特に調整次第で値が変わるものは明記してほしいです。

それと彩度の閾値が255ではなく245なのは意図的ですか？

2022-10-29 15:38 UTC, miyashita64 commented on rear_camera_py/rear_camera/black_extractor.py
> +        result = cv2.inRange(hsv, lower, upper)
`binary_img`とかの方がいいと思います。

2022-10-29 15:38 UTC, miyashita64 commented on rear_camera_py/rear_camera/black_extractor.py
> +import time
消し忘れですか？

2022-10-31 10:21 UTC, sugaken0528 requested changes

2022-10-31 10:21 UTC, sugaken0528 commented on rear_camera_py/rear_camera/black_extractor.py
> +        upper = np.array([180, 255, 255])
```suggestion
        lower = np.array([0, 0, 80]) # 白と識別するための最低HSV値
        upper = np.array([180, 255, 255]) #　白と識別するための最高HSV値
```
シンプルにこれじゃだめ？

2022-11-01 03:19 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/186219)

2022-11-01 04:14 UTC, miyashita64 commented
LGTM!!

2022-11-01 04:26 UTC, sugaken0528 approved these changes
LGTM

2022-11-01 04:44 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-11-02 05:15 UTC, kawanoichi commented on rear_camera_py/tests/test_black_extractor.py
> +@author: kawanoichi
これコピペして使ってるんやろうけど、コピペの場合ってauthorは俺になるの？

2022-11-02 07:16 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/black_extractor.py
> +    print("black_extractor 終了")
ここ消していいんじゃない
テストコードも書いてるし，今の状態だと動かないよね

2022-11-03 01:01 UTC, merged