close #102 リアカメラ映像を取得し、直線を検出する処理をRasPike上で動作させる
KatLab-MiyazakiUniv/etrobocon2022 pull request #151
Opened 2022-10-31 21:54 UTC by Takahiro55555

# チェックリスト

- [X] clang-format している
- [X] コーディング規約に準じている
- [X] チケットの完了条件を満たしている

# 変更点
- リアカメラを用いた角度算出プログラムの追加(Python)
- Python環境関連のファイルを追加

# 動作テスト

## 実験方法
作業ブランチにおいて、#148 のコードを反映することで角度補正を実際に行った。

- 走行体の設置位置：ゲームエリアの中心
- 回頭角度：45度 x 8回（計365度、各々回頭補正を実施）
- 回頭PWM：70
- 回頭補正PWM：60
- 機体番号：01

## 実験結果
ブロック有り無しに関わらず、

### ブロック有
一度目の回頭後の角度補正に失敗している。
具体的には、補正すべき方向とは逆の向きに角度補正を行ってしまっている。

また、ブロックを黒線とご認識することがあった。

https://user-images.githubusercontent.com/31930148/199112263-a99ae839-d152-4306-8fe0-635aaf429b55.MOV

以下、リアカメラ画像と黒線検出結果。番号は回頭回数を示す。
![画像1](https://user-images.githubusercontent.com/31930148/199116076-a2e61195-3a1e-4a4d-bfcc-9cd3b4f0db74.png)

### ブロック無
一度目の回頭後の角度補正に失敗している。
具体的には、補正すべき方向とは逆の向きに角度補正を行ってしまっている。

https://user-images.githubusercontent.com/31930148/199112384-2714c995-72e6-4b6a-8fe3-3217bf98206f.MOV

以下、上記の動画のログファイル。
```
$ cat logfiles/1027-00\:01.txt
SPIKE voltage is 8.362[V] (max voltage: 8.393[V])

On standby.

Signal within 5cm from Sonar Sensor.
31 degree angle correction
-14 degree angle correction
-5 degree angle correction
-19 degree angle correction
-5 degree angle correction
-11 degree angle correction
-10 degree angle correction
The run has been completed

Forced termination.
```

以下、リアカメラ画像と黒線検出結果。番号は回頭回数を示す。

![画像2](https://user-images.githubusercontent.com/31930148/199117259-e78edbd7-c6e0-495b-9a18-174f665f439b.png)

## 備考
走行体02では、`Picamera2`の環境構築が未完了。

## 参考資料
- [実験コード](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/tree/d8635ac0e8677f5ed9923052cfbcb05c74e80697)

2022-11-01 13:27 UTC, kodama0720 commented on rear_camera_py/rear_camera/calibrator.py
> +        height_offset_from_center = h/2.5
計算に使われているそれぞれの数値の意味がよく分かりませんでした。
もう少し各数値に関するコメントが欲しいです。

2022-11-02 05:28 UTC, mutotaka0426 requested changes
レビュー遅れてごめん
まだ途中だけどとりあえずあげとく
指摘っていうよりは疑問がほとんどです

2022-11-02 05:28 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/camera_interface.py
> +        pass
こっちに直接書いたらダメなんだっけ？
というかgetterって必要なの？全体見た感じ使う場面ないみたいだけど後々使うとか？

2022-11-02 05:28 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/camera_interface.py
> +            そのため、可能であればプログラムの初期化処理で1枚だけ試し撮り等をすると、それ以降この関数の処理時間が短くなる.
こういうのはTODOで書いてた方がよくない？

2022-11-02 05:28 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/camera_interface.py
> +        return self.__picam2
propertyの方に直接書いたらダメなんだっけ？

というかgetterって必要？getterってなると外部で使う目的だと思うんだけど，全体見た感じ使う場面ない？
getterじゃなくてシンプルにPicamera2インスタンスの初期化処理とするのじゃダメ？
capture_image()で実行したうえで，`return self.__picam2.capture_array()`にするとか
```suggestion
    def __init_picam2(self) -> None:
        """Picamera2インスタンスの初期化を行う."""
        if self.__picam2 is None:
            picam2 = Picamera2(camera_num=self.__camera_id)
            conf = picam2.create_preview_configuration(
                main={"format": self.__format, "size": self.__size})
            picam2.configure(conf)
            picam2.start()
            self.__picam2 = picam2
```

2022-11-02 11:27 UTC, Takahiro55555 commented on scripts/rear_camera.sh
> +python -m rear_camera --debug $1 $2 $3 $4 $5
`$1 $2 $3 $4 $5` は、`rear_camera.sh`を実行する際に渡されたオプションを、Python側に引き継ぐために設定してる。

デバッグモードは、消し忘れていました...  
修正します。

2022-11-02 11:37 UTC, mutotaka0426 commented on scripts/rear_camera.sh
> +python -m rear_camera --debug $1 $2 $3 $4 $5
角度補正回頭の方でオプション指定特にしないで実行してるけど，今後必要になったら使う用ってこと？

2022-11-02 11:48 UTC, Takahiro55555 commented on scripts/rear_camera.sh
> +python -m rear_camera --debug $1 $2 $3 $4 $5
キャリブレーションを実行する際に、
```
./scripts/rear_camera.sh --calibrate
```
みたいな感じで実行することを想定している。

でも、指定できるオプションの数的に`$5`は余計なので、消します。

2022-11-02 11:49 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/camera_interface.py
> +        return self.__picam2
そもそも、init処理をプライベートにする意味もあまりない気がしてきた...

そうすれば、
> こういうのはTODOで書いてた方がよくない？

の部分のコメントも要らなくなるし。

2022-11-02 15:59 UTC, sugaken0528 requested changes

2022-11-03 20:06 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/camera_interface.py
> +    def start_camera(self) -> Picamera2:
戻り値いらなくない？
48行目も
```suggestion
    def start_camera(self) -> None:
```

2022-11-03 20:10 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/calibrator.py
> +    def _calc_param(self, img: np.ndarray) -> Tuple[np.ndarray, float, float]:
_が一個って原則として外部では使いたくないけど制限はしない～みたいな記法だっけ？
テスト用のために完全なprivateにはしてないって感じ？

2022-11-03 20:12 UTC, mutotaka0426 commented on scripts/rear_camera.sh
> +python -m rear_camera --debug $1 $2 $3 $4
デバッグモード消し忘れてるよ

2022-11-03 22:36 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/calibrator.py
> +    def _calc_param(self, img: np.ndarray) -> Tuple[np.ndarray, float, float]:
この場合は、テストのためという認識であってる。
具体的に自分の開発環境（ラズパイ）の影響もあり、ファイル関連の処理をできるだけ減らしたかったため（ファイル関連処理が遅い）

2022-11-03 22:46 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/186484)

2022-11-05 06:57 UTC, kawanoichi approved these changes
レビュー遅くなって申し訳ありません。
特に問題はないかなと思います。
もうしわけありませんが lock, toml, yamlファイルがいまいちわかってないのでちゃんと見れてません。
LGTM

2022-11-05 07:21 UTC, sugaken0528 approved these changes
LGTM

2022-11-06 04:31 UTC, merged