close#156 ゲームエリア四隅で角度補正が難しい問題の解決
KatLab-MiyazakiUniv/etrobocon2022 pull request #157
Opened 2022-11-07 05:48 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2022-11-07 09:20 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> -        img_gray[0:1, :] = 255
@Takahiro55555 ```img_gray[0:1, :] = 255```この処理がなぜ必要だったか分からなかったのですが、この処理消しても大丈夫でしたか？

2022-11-08 00:49 UTC, mutotaka0426 requested changes
処理の流れについて少しだけ

あと，処理時間とかが分かるなら書いてほしい
マスク処理単体の時間が分かればいいと思う

2022-11-08 00:49 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        # グレースケース画像に変換
```suggestion
        # グレースケール画像に変換
```

2022-11-08 00:49 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        binary_img = BlackExtractor.extract_black(mask_img)
これって分ける意味ある？
マスク処理の中でグレースケール画像に変換する処理があるけど，それが白黒画像変換になるのはなにか不都合ある？

2022-11-08 03:25 UTC, kodama0720 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        circles = np.delete(circles[0], np.where(circles[0, :, 1] < thre)[0], axis=0)
これ何でだっけ？
あとthreってどういう意味？

2022-11-08 04:38 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> -        img_gray[0:1, :] = 255
多分大丈夫（自分の今作業しているコードでも消してる...）

2022-11-08 04:39 UTC, Takahiro55555 commented
`rear_camera_py/tests/test_data/test_binary_image.png`は、テストの際に生成されるファイルだから不要説無い？

2022-11-08 06:42 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        # グレースケース画像に変換
円を一カ所検出した場合、0.04~0.08sぐらいです

2022-11-08 07:21 UTC, sugaken0528 approved these changes
LGTM

2022-11-08 07:51 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/177006)

2022-11-08 08:08 UTC, miyashita64 approved these changes
LGTM!!

2022-11-08 08:08 UTC, merged