close #152 リアカメラシステムの処理時間の短縮と黒線抽出処理の統合
KatLab-MiyazakiUniv/etrobocon2022 pull request #163
Opened 2022-11-08 20:59 UTC by Takahiro55555

# チェックリスト

- [X] clang-format している
- [X] コーディング規約に準じている
- [X] チケットの完了条件を満たしている

# 変更点
- ラズパイ起動時にリアカメラシステムを起動するUnitファイルを作成
- `nc`コマンドを実行することで黒線検出・角度算出処理を呼び出す方式に変更し、高速化

# 動作テスト
## 実験方法
1. 100秒間連続して角度算出処理を呼び出すことで平均処理時間を算出する 
2. 実機で角度補正を実行できることを確認する

## 実験データ
### 1. 100秒間連続して角度算出処理を呼び出すことで平均処理時間を算出する
以下、のコマンドを実行することで100秒間の角度算出処理の回数を算出することができる（具体的にはファイルに書き出された角度算出処理結果の行数を数えている）。
このように計測・算出した値を利用して平均処理時間を簡易的に算出する。
```
timeout 100 bash -c 'while $true; do ./scripts/rear_camera.sh; echo ''; done' > tmp.txt || cat tmp.txt | wc -l
```

#### 非デバッグモード、マスク処理有、走行体03（4GB RAM）
平均処理速度：`2.83[fps]` (1回あたり約 `353.35[ms]`)

#### デバッグモード、マスク処理有、走行体03（4GB RAM）
平均処理速度：`0.66[fps]` (1回あたり約 `1515.15[ms]`) 

#### 非デバッグモード、マスク処理無、走行体01
平均処理速度：`5.97[fps]` (1回あたり約 `167.50[ms]`)
※参考値

### 2. 実機で角度補正を実行できることを確認する
[実験時のコード](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/tree/342a54f898638bd118eeb0fdc40c83568a406776)

45度回転の度に1回PWM`65`で回頭補正を行う。これを8回繰り返した。
以下の動画から、角度補正処理が実行されていることを確認した。

https://user-images.githubusercontent.com/31930148/200672550-64dae966-756b-4491-b88a-8ab0ddedd438.MOV

最初の角度補正で補正すべき向きと逆向きに補正してしまっているが、初期位置が悪く補正限界を超えてしまったのではないかと考えているが、確証はない。

2022-11-09 01:02 UTC, mutotaka0426 commented
走行体03って？
走行体2のこと？

2022-11-09 04:24 UTC, Takahiro55555 commented
> 走行体03って？ 走行体2のこと？

リモート開発用の走行体（Spikeと接続されてはいるが実際には走れない）のことです。
実際に走れないこと点を除いて、実際の走行体との差異はRAMのサイズが半分の4GBという点のみです。

2022-11-09 14:14 UTC, kodama0720 requested changes

2022-11-09 14:14 UTC, kodama0720 commented on rear_camera_py/tests/test_angle_server.py
> +        # NOTE: また、サーバを終了しても使用していたポートはデフォルトで60秒間はTIME_WAIT状態になり、
```suggestion
        # NOTE: サーバを終了しても使用していたポートはデフォルトで60秒間はTIME_WAIT状態になり、
```

2022-11-09 14:14 UTC, kodama0720 commented on rear_camera_py/tests/test_angle_server.py
> +        # NOTE: 上記のテストで使ったポートが解放されていない可能背があるため、
```suggestion
        # NOTE: 上記のテストで使ったポートが解放されていない可能性があるため、
```

2022-11-09 14:14 UTC, kodama0720 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +            KeyError: パラメータフィルの内容に期待するキーのデータが無い場合に発生
```suggestion
            KeyError: パラメータファイルの内容に期待するキーのデータが無い場合に発生
```

2022-11-10 13:42 UTC, mutotaka0426 commented on scripts/rear_camera.sh
> +fi
`start_rerar_camera.sh`でキャリブレーションを実行することもできるし，サーバー立てた状態なら`rear_camera.sh`からもキャリブレーションをいつでも実行できるって認識で会ってる？

あと個人的にポート番号は17行目と同様に書いた方がいいと思う
最初にデフォルト値の定数（変数）を用意しておくとか

2022-11-10 14:39 UTC, Takahiro55555 commented on scripts/rear_camera.sh
> +fi
> `start_rerar_camera.sh`でキャリブレーションを実行することもできるし，サーバー立てた状態なら`rear_camera.sh`からもキャリブレーションをいつでも実行できるって認識で会ってる？

大体あってるけど、正確には以下のような感じで排他的にしか利用できないです。
|サーバの状態| |
|---|---|
|起動時|`rear_camera.sh`でキャリブレーションする（`start_rerar_camera.sh`でキャリブレーションは不可）|
|停止時|`start_rear_camera.sh`でキャリブレーションする（`rerar_camera.sh`でキャリブレーションは不可）|

2022-11-10 15:40 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/133449)

2022-11-11 10:27 UTC, kodama0720 approved these changes
LGTM!

2022-11-11 12:17 UTC, Takahiro55555 commented
先に #164 をマージしたいので、もしマージ可能になっても待っていただけると助かります。

2022-11-11 14:35 UTC, kawanoichi approved these changes
遅くなりました。すみません
LGTM

2022-11-12 10:13 UTC, Takahiro55555 commented
#### 非デバッグモードでの処理時間（リモート開発用の走行体、RAM 4GB）

| | 直線検出処理変更前 | 直線検出処理変更後 |
|---|---|---|
|FPS[fps]|2.83|3.75|
|処理時間[ms]|353.35|266.67|

以下、計測用コマンド（プルリク時の計測方法と同一）
```
timeout 100 bash -c 'while $true; do ./scripts/rear_camera.sh; echo ''; done' > tmp.txt || cat tmp.txt | wc -l
```

2022-11-12 11:00 UTC, miyashita64 approved these changes
LGTM!!

2022-11-12 11:01 UTC, merged