close #162 角度補正のためのライン検出方法の変更
KatLab-MiyazakiUniv/etrobocon2022 pull request #164
Opened 2022-11-09 21:32 UTC by kawanoichi

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
##以下の問題に対処する
- 撮影する角度によって、交点が円と判定できない場合があり、mask処理が行われない場合がある
![image.png](https://images.zenhubusercontent.com/62aae97470ad089508512e5b/6cd5b0a1-1b4b-42fe-8f8d-498decf79511)
- 手前の線がブロックで隠れて、面積が小さくなってしまった場合、ベースサークルにつながる線が採用されてしまう
![image.png](https://images.zenhubusercontent.com/62aae97470ad089508512e5b/aa71c349-941c-4255-99ae-77573ac96d8e)
-射影変換によってできた画像の枠を直線として判定してしまう
![image](https://user-images.githubusercontent.com/96767490/200945639-6a5e2fd1-3d52-4b0a-9aef-250b01dc2fb3.png)
##変更点
- 面積からラインの角度を求めるのでなく、ラインの辺(線分)を取得して、辺から角度を取得する。
- mask処理は完全削除

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2022-11-09 22:28 UTC, Takahiro55555 commented
コードと動作テストの画像を見る限り、処理内容に問題は無いと思います！

輪郭抽出は黒線抽出が不完全でノイズを取り除くために使ってたけど、今は問題なく黒線のみを抽出できるようになったから、確かに要らないね...

処理速度も速くなってるっぽいし、角度算出の精度も向上していて大改善だと思います！
ありがとうございます!!!

2022-11-10 00:07 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        lines = lines[np.where((lines[:, :, 1] > ignore_border) & (lines[:, :, 3] > ignore_border))]
`self.runner_base_coordinate_to_image_base_coordinate_pix`関数を使うと、走行体の中心からの座標[mm]を画像上の座標[pix]に変換できるので、検出領域を変更したくなった時の指定が少し楽になるかも？

あと、射影変換のパラメータの変更等で射影変換の際、元画像を拡大するようにパラメータを変更した際などの、影響を吸収できるようになる。
ただ、カメラの角度が変わるだけでは何の影響もないので、余裕がない場合はこのままでもいい気がします。

以下、コード例（未検証）
```suggestion
        # 走行体の中心から600mmより上にある線、もしくは、またがってる線分を削除
        img_h, img_w= img.shape[:2]
        _, ignore_border = self.runner_base_coordinate_to_image_base_coordinate_pix(0, 600, img_h, img_w)
        lines = lines[np.where((lines[:, :, 1] > ignore_border) & (lines[:, :, 3] > ignore_border))]
```


同様に、`self.mm_to_pix`関数を利用すると引数の`length_threshold`とかの単位を`mm`で指定できます。

以下、走行体を基準にした座標と画像座標の関係。
![basic-coordinates](https://user-images.githubusercontent.com/31930148/200966845-235cccda-9320-4c43-8122-cb94a63e587e.png)

2022-11-10 14:45 UTC, mutotaka0426 requested changes
プルリク見た感じかなりいいと思う！
コードも処理は取り合えず気になるところはなかったかな

名前の付け方とかが気になったくらいです

2022-11-10 14:45 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_line: np.ndarray,
関数名に合わせるなら`detected_line`じゃない
その方が変数名っぽいし

2022-11-11 01:33 UTC, Takahiro55555 reviewed
線分を検出する際の長さをmmで指定するのはどうでしょうか？

デフォルト値は、`mm_to_pix`関数のテストコードにわざと現状のデフォルト値`50`(pix)を入力して、テストを失敗させればすぐに算出できるのではないかと考えます。

2022-11-11 01:33 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        length_threshold: int = 50,
線分を検出する際の長さを`mm`で指定するのはどうでしょうか？
後から値を調整したくなった際に、より直感的に指定できると思います。

```suggestion
        length_threshold_mm: int = 50,
```

2022-11-11 01:33 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +            length_threshold (int): 線分を検出する際の長さ閾値(これより短い線は除外)
同上
```suggestion
            length_threshold_mm (int): 線分を検出する際の長さ閾値(これより短い線は除外)
```

2022-11-11 01:33 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        # 線分検出モジュールのインスタンス化
同上

```suggestion
        length_threshold = int(self.mm_to_pix(length_threshold_mm))
        # 線分検出モジュールのインスタンス化
```

2022-11-11 06:18 UTC, mutotaka0426 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +            # 枠(直線)との距離が length_threshold より小さい座標を除外する
`distance_threshold`じゃないの？
`length_threshold`って線の長さの閾値でしょ？

2022-11-11 09:32 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/187405)

2022-11-11 09:52 UTC, kawanoichi reviewed
プルリクの検証結果の内容を更新しました。
また実行時間が 0.06s → 0.2s以下になりました。(debugなし)

2022-11-11 09:53 UTC, Takahiro55555 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +            # 枠(直線)との距離が length_threshold より小さい座標を除外する
自分は、ノイズとして除外する線の長さを`mm`で指定出来たら便利かなと思い`length_threshold`を`mm`で指定する提案をしたけど、もしかして自分が勘違いしてた感じかな？

2022-11-11 09:55 UTC, Takahiro55555 commented
> プルリクの検証結果の内容を更新しました。 また実行時間が`0.06 → 0.2s以下`になりました。(debugなし)

そういえば、実行環境を聞いてなかったけど実際の走行体（Raspberry Pi）上で計測した結果という認識で合ってる？

2022-11-11 09:59 UTC, kawanoichi commented
@Takahiro55555 
すみません、僕のパソコン上の処理速度です。
大きく違ったりしますか？

2022-11-11 10:02 UTC, kawanoichi commented
> @Takahiro55555 すみません、僕のパソコン上の処理速度です。 大きく違ったりしますか？



> > プルリクの検証結果の内容を更新しました。 また実行時間が`0.06 → 0.2s以下`になりました。(debugなし)
> 
> そういえば、実行環境を聞いてなかったけど実際の走行体（Raspberry Pi）上で計測した結果という認識で合ってる？

2022-11-11 10:16 UTC, Takahiro55555 commented
> @Takahiro55555 すみません、僕のパソコン上の処理速度です。 大きく違ったりしますか？

PCにもよるけど、ラズパイより性能が高いことのほうが一般的なのでラズパイのほうが遅くなるかなと思ったけど、実際に計測してみたらそこまででもないみたい...

今、ラズパイ環境で実際のカメラから映像を取得して角度算出までの時間を計測してみたけど`280[ms]`以内には処理が終了するみたい。
輪郭検出を利用するバージョンで同じように計測したところ`400[ms]`程度を要するので、問題なく高速化できてるっぽいです。

2022-11-11 10:22 UTC, kawanoichi commented
> > @Takahiro55555 すみません、僕のパソコン上の処理速度です。 大きく違ったりしますか？
> 
> PCにもよるけど、ラズパイより性能が高いことのほうが一般的なのでラズパイのほうが遅くなるかなと思ったけど、実際に計測してみたらそこまで大きな差は無いみたい...
> 
> 実際に、ラズパイ環境で実際のカメラから映像を取得して角度算出までの時間を計測してみたら`280[ms]`以内には処理が終了することを確認しました(n=4)。 また、輪郭検出を利用するバージョンで同じように計測したところ`400[ms]`程度を要するので、問題なく高速化できてるっぽいです。

すみません、ありがとうございます。

2022-11-11 11:56 UTC, miyashita64 requested changes
お疲れ様です。
処理はいいと思います。

主にコメントで気になったので、対応お願いします。
気に入らないものはそのままでいいです。

2022-11-11 11:56 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        #  jsonファイルの読み込み
```suggestion
        #  jsonファイル(リアカメラのキャリブレーション情報)の読み込み
```
間違ってたらごめん

2022-11-11 11:56 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +                      detected_line[1] - detected_line[3]])
```suggestion
        a = np.array([detected_line[0] - detected_line[2],
                      detected_line[1] - detected_line[3]])
```

2022-11-11 11:56 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        # 走行体からの距離(detect_dist_from_rbody(mm))までの間(画像に写る)の線分だけ残す
```suggestion
        # 走行体からの距離(detect_dist_from_rbody_mm)までの間(画像に写る)の線分だけ残す
```

2022-11-11 11:56 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +                continue
なくていいと思います
```suggestion
```

2022-11-11 11:56 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +                continue
同じく
```suggestion
```

2022-11-11 11:56 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        # pix_xを求める
```suggestion
        # 画像上のx座標(pix_x)を求める
```

2022-11-11 11:56 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        # pix_yを求める
```suggestion
        # 画像上のy座標(pix_y)を求める
```

2022-11-11 11:58 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
これはどういう数値ですか？

2022-11-11 12:10 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
```交点toブロック置き場*2+補正値```の意味がわからいという話ですか？

2022-11-11 12:15 UTC, Takahiro55555 approved these changes
LGTM!!!
指摘されている点以外は大丈夫だと思います！

お疲れ様です。

2022-11-11 12:16 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
なぜ、この長さを使っているか、です。

2022-11-11 12:49 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
これでわかりますか？
![S__1794050](https://user-images.githubusercontent.com/96767490/201343329-eff471b3-898e-4148-9779-6d5391feb754.jpg)
補正値を入れる理由は
- ギリギリの値をつかいたいくない
- 実際の値を使って表示させた``` ignore_border ```の場所に思っていた場所と少しズレがあった(理由はわかりません)
他に案があったら言ってください

2022-11-11 12:55 UTC, sugaken0528 requested changes
全体的に良いと思います

2022-11-11 12:55 UTC, sugaken0528 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        distance_threshold: float = 1.41421356,
何か数値の根拠とかあったりする？
あったらコメントしてくれるとありがたいと思う

2022-11-11 12:55 UTC, sugaken0528 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +            0, detect_range_from_rbody_mm, img_h, img_w)
```suggestion
            0, detect_range_from_rbody_mm, img_h, img_w) # 検出する範囲の境界線
```

2022-11-11 12:55 UTC, sugaken0528 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        lines = lines[np.where((lines[:, :, 1] > ignore_border) & (lines[:, :, 3] > ignore_border))]
```suggestion
        lines = lines[np.where((lines[:, :, 1] > ignore_border) & (lines[:, :, 3] > ignore_border))] # 線分のy座標が2点とも境界線より大きい線分を取得 ※型: [[x1,y1,x2,y2],...]
```
個人的に読み辛いって感じたから説明的なコメントあった方がいい気がした。(スルーでもおけ)
型が変わってることは書いといた方がいい

2022-11-11 12:58 UTC, sugaken0528 requested changes

2022-11-11 13:01 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        _, ignore_border = self.runner_base_coordinate_to_image_base_coordinate_pix(
ミスではないです。
pix_yだけ使うという意味です。

2022-11-11 13:05 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        distance_threshold: float = 1.41421356,
```length_threshold_mm: int = 80```はArgsの通りです。分かりにくいですか？
``` distance_threshold: float = 1.41421356 ``` は僕が考えたのではなく``` cv2.ximgproc.createFastLineDetector ```の　規定値です。

2022-11-11 13:23 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
補正値は足し算じゃなくて倍率にした方がいいような気もしてきた

2022-11-11 13:32 UTC, sugaken0528 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        distance_threshold: float = 1.41421356,
distance_thresholdが気になっただけ

2022-11-11 13:37 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
倍率かは任せる。

個人的には、補正値より余白(110mm)とかの方がわかりやすい。あと、181mmは交点の長さ含んでなかった気がするから、ずれはそのせいかも。

2022-11-11 13:42 UTC, kawanoichi commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
距離 J って交点考慮してないの？
![image](https://user-images.githubusercontent.com/96767490/201352266-7f391368-6aeb-4d8f-a6cf-7a7cd06d81c2.png)

2022-11-11 13:43 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        detect_range_from_rbody_mm = 181*2+110  # 検出する範囲 (交点toブロック置き場*2+補正値)
たぶん手前の交差点まで

2022-11-11 13:51 UTC, miyashita64 commented on rear_camera_py/rear_camera/line_angle_calculator.py
> +        # 画像上のx座標(pix_y)を求める
```suggestion
        # 画像上のy座標(pix_y)を求める
```

2022-11-11 14:02 UTC, sugaken0528 approved these changes
LGTM

2022-11-11 14:05 UTC, miyashita64 approved these changes
LGTM!!

2022-11-12 05:24 UTC, merged