close #6 モーターを動かす
KatLab-MiyazakiUniv/etrobocon2022 pull request #18
Opened 2022-06-14 09:22 UTC by sap2368

2022-06-14 10:39 UTC, Takahiro55555 commented
変更点やどのようにテスト（シミュレータなのか実機なのか等の具体的なテスト方法）なのか、プルリクエストの説明を記述していただけると助かります。m(_ _)m

2022-06-14 20:44 UTC, sugaken0528 requested changes
どういった値でどんな動作確認を行ったのか。あと動作系のissueは各パラメータに対して走行体がどんな動きをしたかを動画で示してくれると皆んながわかりやすいし説得力が増すからやって欲しい。pull requests送るときに動画のリンクとかを貼っつけると良いよ!!

2022-06-14 20:44 UTC, sugaken0528 commented on module/EtRobocon2022.cpp
> +    }
動作確認用に書いたコードは、今後みんなが消したりしなきゃいけなくなるから消した状態でpushせんといかん。

2022-06-14 20:44 UTC, sugaken0528 commented on module/EtRobocon2022.h
> +#include "Controller.h"
いずれ使うやろうけど今の時点では必要ないからいらないかと

2022-06-14 20:44 UTC, sugaken0528 commented on test/dummy/ev3api_motor.h
> +} motor_type_t;
フォーマットが変だね。clang-formatの設定ってまだやってないんだっけ?

2022-06-14 20:44 UTC, sugaken0528 commented on test/dummy/Clock.h
> +#endif
現時点でClockいるっけ?
まだいらないなら追加するべきじゃないかと。

2022-06-14 21:21 UTC, sugaken0528 requested changes

2022-06-14 21:21 UTC, sugaken0528 commented on module/API/Controller.cpp
> + * @brief モーター制御
Measurerクラスの方に合わせたいので「モーター制御に用いる関数をまとめたラッパークラス」に変更をお願いします

2022-06-14 21:21 UTC, sugaken0528 commented on module/API/Controller.h
> + * @brief モーター制御
ここも

2022-06-14 23:34 UTC, miyashita64 reviewed
内容は問題なさそうです。
主にドキュメントコメントのauthorについてと指摘されているところの修正をお願いします。

2022-06-14 23:34 UTC, miyashita64 commented on app.cpp
> + * @author sakakibara
authorはファイルを触った人を記録しておきたいので、
miyashita64, sakakibara
のように追加するようにしてください。

2022-06-14 23:34 UTC, miyashita64 commented on app.h
> + * @author sakakibara
ここは編集してないなら追記する必要はないです

2022-06-14 23:34 UTC, miyashita64 commented on module/EtRobocon2022.cpp
> + * @author sakakibara
ここも

2022-06-14 23:34 UTC, miyashita64 commented on module/EtRobocon2022.h
> + * @author sakakibara
ここも

2022-06-14 23:34 UTC, miyashita64 commented on test/EtRobocon2022Test.cpp
> + * @author sakakibara
編集してないなら変えなくて大丈夫

2022-06-14 23:34 UTC, miyashita64 commented on test/dummy/Port.h
> + */
このコメントはなくてもいいと思う。
ドキュメントコメントが複数あるとわかりづらい。

2022-06-15 04:05 UTC, sap2368 commented on test/dummy/ev3api_motor.h
> +} motor_type_t;
まだやってないと思います

2022-06-15 04:21 UTC, sap2368 commented on test/dummy/ev3api_motor.h
> +} motor_type_t;
勉強会第2回でやってました

2022-06-15 04:22 UTC, sugaken0528 commented on test/dummy/ev3api_motor.h
> +} motor_type_t;
よろしく!

2022-06-15 10:14 UTC, Takahiro55555 commented
コミットメッセージですが、何を変更したかわかりやすいメッセージを記述していただけると助かります。
先ほど、@kodama0720 が[Wiki](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88)にコミットメッセージの書き方を記述してくれました。
お手数ですが[Wiki](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88)を参考に、最新のコミットメッセージだけでも修正していただけると幸いです。

2022-06-15 10:22 UTC, Takahiro55555 requested changes
ちなみに、直前のコミットメッセージの変更方法は以下のコマンドでできると思います。

```
git commit --amend -m "ここに修正したコミットメッセージ"
```

[参考サイト](https://www.granfairs.com/blog/staff/git-commit-fix)

2022-06-16 01:15 UTC, kodama0720 commented on app.cpp
> + * @author miyasita64
細かいけどmiyashita64?

2022-06-16 01:15 UTC, kodama0720 commented on app.h
> + * @author miyasita64
ここも

2022-06-16 01:15 UTC, kodama0720 commented on module/API/Controller.h
> + * @author sakakibara
ふと思いましたが、authorはgithubアカウント名で揃えた方がよかったでしょうか？
今のままの方が個人を特定しやすい気はしますが

2022-06-16 07:02 UTC, kodama0720 approved these changes
LGTM!

2022-06-16 07:04 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/18843)

2022-06-16 07:07 UTC, sugaken0528 approved these changes
LGTM

2022-06-16 07:10 UTC, merged