Ticket 21
KatLab-MiyazakiUniv/etrobocon2022 pull request #28
Opened 2022-06-23 06:29 UTC by sugaken0528

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- StraightRunnerクラスとRotationクラスを追加

# 動作テスト
- runStraightToDistanceメソッド(指定した距離まで直進)とrotateRightメソッド(指定した角度右に回頭)の動作を確認

## 実験方法

## 実験データ
- 実機では動かない
- シミュレータでは同じ挙動をする

## 実験結果
https://1drv.ms/v/s!AiAcrWC-huU9g0KCfWV94mAM6ig_
## 添付資料

2022-06-27 00:21 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +    printf("warning: The pwm value passed to LineTracer::run is 0\n");
```suggestion
    printf("warning: The pwm value passed to Rotation::rotateLeft is 0\n");
```

2022-06-27 00:21 UTC, miyashita64 requested changes
処理はいいと思います。
includeの場所や関数名の修正をお願いします。

2022-06-27 00:21 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +//右回転
右回頭の方がわかりやすいと思います。

2022-06-27 00:21 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +//左回転
左回頭の方がわかりやすいと思います。

2022-06-27 00:21 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +double Rotation::calculate(int angle)
何をしているか完全に理解できてませんが、calculateMoterCount()などの方がわかりやすいと思います。

2022-06-27 00:21 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +    printf("warning: The pwm value passed to LineTracer::run is 0\n");
```suggestion
    printf("warning: The pwm value passed to Rotation::rotateRight is 0\n");
```

2022-06-27 00:21 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +    printf("warning: The pwm value passed to LineTracer::run is 0\n");
```suggestion
    printf("warning: The pwm value passed to Rotation::turnForwardRightPivot is 0\n");
```

2022-06-27 00:22 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +    printf("warning: The pwm value passed to LineTracer::run is 0\n");
```suggestion
    printf("warning: The pwm value passed to Rotation::turnBackRightPivot is 0\n");
```

2022-06-27 00:22 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +    printf("warning: The pwm value passed to LineTracer::run is 0\n");
```suggestion
    printf("warning: The pwm value passed to Rotation::turnForwardLeftPivo is 0\n");
```

2022-06-27 00:22 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +    printf("warning: The pwm value passed to LineTracer::run is 0\n");
```suggestion
    printf("warning: The pwm value passed to Rotation::turnBackLeftPivot is 0\n");
```

2022-06-27 00:23 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +#include "stdio.h"
これはStraightRunner.hに

2022-06-27 00:24 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +  int rightSign = -1;
他の動作では、調整のため？に左右で処理が異なる部分もあるので、絶対に統一した方がいいかというと微妙ですね...

2022-06-27 00:29 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +  : RADIUS(45.0), TREAD(140), ROTATE_MIN_PWM(50), PIVOT_FRONT_MIN_PWM(50), PIVOT_BACK_MIN_PWM(50)
これは実機でちゃんと図った値ってことで大丈夫だよね？

2022-06-27 00:33 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +#include "stdio.h"
.hの方に移動させたほうがいいのと，以下のように記述した方がいい
```suggestion
#include <stdio.h>
```

2022-06-27 00:34 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +#include "stdio.h"
ここも

2022-06-27 00:41 UTC, mutotaka0426 commented on module/Motion/StraightRunner.h
> +  StraightRunner();
このクラスstaticクラスにしていいんじゃないかな
このクラスのインスタンスを作る必要がない気がする

staticクラスにする場合は，インスタンス化を禁止するために.cppのコンストラクタを削除して，.hのコンストラクタをprivateに持っていけばできる

2022-06-27 00:42 UTC, mutotaka0426 commented on test/StraightRunnerTest.cpp
> +namespace etrobocon2021_test {
```suggestion
namespace etrobocon2022_test {
```

2022-06-27 00:43 UTC, mutotaka0426 commented on test/StraightRunnerTest.cpp
> +}  // namespace etrobocon2021_test
```suggestion
}  // namespace etrobocon2022_test
```

2022-06-27 00:46 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +                                                        : PIVOT_FRONT_MIN_PWM;
248行目と同じようにコメントは入れてあげたほうがいい
特にここら辺は分かりづらいし
```suggestion
    //徐々に速度を遅くする処理
    double leftCountRate = 1 - (abs(measurer.getLeftCount()) / targetMotorCount);
    leftPwm = pwm * leftCountRate > PIVOT_FRONT_MIN_PWM ? (int)(pwm * leftCountRate)
                                                        : PIVOT_FRONT_MIN_PWM;
```

2022-06-27 00:47 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +                                                        : PIVOT_FRONT_MIN_PWM;
ここも

2022-06-27 00:47 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +    controller.setRightMotorPwm(abs(rightPwm) * rightSign);
これも徐々に遅くする処理だよね？

2022-06-27 00:48 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +    printf("warning: The pwm value passed to LineTracer::run is 0\n");
```suggestion
    printf("warning: The pwm value passed to StraightRunner::runStraightToDistance is 0\n");
```

2022-06-27 00:51 UTC, mutotaka0426 commented on module/Motion/Rotation.h
> +  Rotation();
これもstaticクラスにしていい気がする
動作系のクラスってインスタンス化する意味ってあるかな？

2022-06-27 00:52 UTC, mutotaka0426 commented on module/Motion/Rotation.cpp
> +                                                          : PIVOT_FRONT_MIN_PWM;
ここも

2022-06-27 00:54 UTC, mutotaka0426 commented on test/RotationTest.cpp
> +namespace etrobocon2021_test {
```suggestion
namespace etrobocon2022_test {
```

2022-06-27 00:54 UTC, mutotaka0426 commented on test/RotationTest.cpp
> +}  // namespace etrobocon2021_test
```suggestion
}  // namespace etrobocon2022_test
```

2022-06-27 00:57 UTC, mutotaka0426 requested changes
処理自体はそこまで気にならなかったけど，ちょっと説明不足なところがある
特にRotationは結構複雑なことしてるからコメントをちゃんと入れてあげないと，レビューがかなりきついと思う

2022-06-27 12:57 UTC, mutotaka0426 commented
> 処理自体はそこまで気にならなかったけど，ちょっと説明不足なところがある 特にRotationは結構複雑なことしてるからコメントをちゃんと入れてあげないと，レビューがかなりきついと思う

2022-06-27 12:58 UTC, mutotaka0426 commented
> > 処理自体はそこまで気にならなかったけど，ちょっと説明不足なところがある 特にRotationは結構複雑なことしてるからコメントをちゃんと入れてあげないと，レビューがかなりきついと思う

2022-06-27 13:03 UTC, mutotaka0426 commented
失敬，間違ってcloseしてしまった

2022-06-28 12:09 UTC, mutotaka0426 requested changes
一つ追加で気になったところ

2022-06-28 12:32 UTC, mutotaka0426 requested changes
ごめんもう一つ追加で

2022-06-28 12:32 UTC, mutotaka0426 commented on module/Motion/StraightRunner.h
> +  void runStraightToDistance(double targetDistance, int pwm);
関数名runだけじゃダメかな？
StraghtRunnerクラスのrunってことだけだと伝わらない？

LineTracerクラスではrunにしてるんだけど，どっちかに統一した方がいいと思う

2022-06-28 14:33 UTC, miyashita64 reviewed
いくつかのコメント漏れとstd::max()で三項演算子が消せるところがありました。
三項演算子は無理に減らす必要はないかもしれません。

それと、このチケットでやることではないと思いますが、pwmが0になった際のwarningは専用のクラス？を作る方がいいと思いました。

2022-06-28 14:33 UTC, miyashita64 commented on module/API/Controller.cpp
> +void Controller::resetMotorCount()
形式的に関数の上に説明が欲しいです。

```suggestion
// モータの回転数を初期化
void Controller::resetMotorCount()
```

2022-06-28 14:33 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +                       : ROTATE_MIN_PWM;
```suggestion

    // #include <algorithm>が必要

    int leftPwm = std::max(diffLeftDistance / targetDistance * pwm, ROTATE_MIN_PWM)
    int rightPwm = std::max(diffRighrDistance / targetDistance * pwm, ROTATE_MIN_PWM)
```

の方がすっきりしそうです。

2022-06-28 14:33 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +    leftPwm = pwm * leftCountRate > PIVOT_FRONT_MIN_PWM ? (int)(pwm * leftCountRate)
std::max()でも可能

2022-06-28 14:33 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +                                                        : PIVOT_FRONT_MIN_PWM;
std::max()でも可能

2022-06-28 14:33 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +                                                          : PIVOT_FRONT_MIN_PWM;
std::max()でも可能

2022-06-28 14:33 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +                                                          : PIVOT_FRONT_MIN_PWM;
std::max()でも可能

2022-06-28 14:33 UTC, miyashita64 commented on module/Motion/Rotation.cpp
> +
形式的にコメントが欲しいです。

2022-06-28 14:33 UTC, miyashita64 commented on test/StraightRunnerTest.cpp
> + *  @author mutotaka0426
ここは武藤さんであってますか？

2022-06-28 19:36 UTC, mutotaka0426 requested changes
何回にも分けてレビューして申し訳ないけどよろしく

2022-06-28 19:36 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +// 設定された距離を直進する
.hと合わせた方がいい
```suggestion
// 指定された距離を直進する
```

2022-06-28 19:36 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +  double initialDistance = Mileage::calculateMileage(initialRightMotorCount, initialLeftMotorCount);
回頭ではresetMotorCount()使ってるけど，どっちかに合わせた方がいい
後日LineTracerの方も合わせるけど，同じプルリクで出してる回頭と直進は合わせてほしい

2022-06-28 19:36 UTC, mutotaka0426 commented on test/StraightRunnerTest.cpp
> +    rightInitial = Mileage::calculateWheelMileage(rightAngle);
ここも

2022-06-28 19:58 UTC, mutotaka0426 commented on test/StraightRunnerTest.cpp
> +    EXPECT_GE(differenceError, std::abs(leftDifference - rightDifference));
expectedに対するのはactualにするようにコーディング規約に書いてるよ

2022-06-28 20:56 UTC, mutotaka0426 commented on module/Motion/Rotation.h
> +  Rotation();
って思ってたけど，LineTracerがエッジをメンバに持ってるように，何を持つか分らんしインスタンス化していい気がしてきた．
なのでこのままでいいです．staticクラスにするのは計算機系とかfacadeパターンのときだけかな

2022-06-29 03:25 UTC, kodama0720 commented on module/Motion/StraightRunner.cpp
> +      currentPwmInt = (int)currentPwm;
キャストは必要ない気がします

2022-06-29 06:11 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +  if(targetDistance < 0 || pwm == 0) return;
異常終了するときは16-18行目みたいなやつを入れてほしい

2022-06-29 06:35 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +      currentPwm = MIN_PWM + (ACCELE_PWM * count) * ((pwm > 0) ? 1 : -1);
`(pwm > 0 ? 式1 : 式2)`みたいな形だったらいいけど，計算の中で条件演算子を使うのって個人的に可読性が下がるように思うんだけど，下のようにしたらダメ？
気に入らなかったらこのままでもいいけど

```suggestion
      currentPwm = MIN_PWM + (ACCELE_PWM * count) * (pwm / std::abs(pwm));
```

2022-06-29 12:33 UTC, kodama0720 commented on module/Motion/StraightRunner.cpp
> -  if(targetDistance < 0 || pwm == 0) return;
これを消しているのは前進・後退の両方に対応するためですか？

2022-06-29 12:33 UTC, kodama0720 commented on module/Motion/Rotation.cpp
> +    controller.sleep();
sleepの位置を変えると、ごくわずかな誤差ではありますが10ミリ秒分ループから抜けるのが遅くなると思います

2022-06-29 12:33 UTC, kodama0720 commented on module/Motion/Rotation.cpp
>      controller.sleep();
ここも？

2022-06-29 12:35 UTC, kodama0720 commented on module/Motion/StraightRunner.cpp
> -  if(targetDistance < 0 || pwm == 0) return;
あ、すみません
上の方に代わりの処理が書いてありました

2022-06-29 17:19 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/100549)

2022-06-30 01:49 UTC, kodama0720 approved these changes
LGTM!

2022-06-30 03:28 UTC, kawanoichi approved these changes
LGTM

2022-06-30 06:38 UTC, merged