close #22 色を判別する
KatLab-MiyazakiUniv/etrobocon2022 pull request #29
Opened 2022-06-23 06:57 UTC by mutotaka0426

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- 色を識別するColorJudgeクラスを追加
- ColorJudgeクラスのテストコードを追加
- カラーセンサのポート番号を修正
- measurerクラスの不要な関数を消去

# 動作テスト
- 実機を各色の上においてColorJudge::getColor()を呼び出して正しい色が返ってくることを確認

# 問題点
- 黒と白の境界の色を取得する時，どうしても緑や青と認識してしまう場合がある
- 多数決方式で色を決定する手法などで解決できるかも？（5回取得した内で一番多い色を採用する等）

## 添付資料
[HSV変換の資料](https://tomari.org/main/java/color/ccal.html)

2022-06-26 19:46 UTC, Takahiro55555 requested changes
テストコードの年数(2021)の部分は修正をお願いします。

2022-06-26 19:46 UTC, Takahiro55555 commented on test/ColorJudgeTest.cpp
> +namespace etrobocon2021_test {
```suggestion
namespace etrobocon2022_test {
```

2022-06-26 19:46 UTC, Takahiro55555 commented on test/ColorJudgeTest.cpp
> +}  // namespace etrobocon2021_test
```suggestion
}  // namespace etrobocon2022_test
```

2022-06-26 19:46 UTC, Takahiro55555 commented on module/Motion/ColorJudge.cpp
> +// RGBをHSVに変換する
```suggestion
// RGBをHSVに変換する
// 参考: https://tomari.org/main/java/color/ccal.html
```

Wikipedia等では、最も小さな値を基準に値を算出していたりと、サイトによって式が微妙に違うようです？
なので、参考にしたサイトをコメント中に記述したほうが、来年以降コードを使う人が混乱しにくいかもしれません。

2022-06-26 22:52 UTC, kawanoichi approved these changes
LGTM

2022-06-26 23:30 UTC, miyashita64 approved these changes
@Takahiro55555 が指摘されているところ以外はいいと思います。
![LGTM](https://image.lgtmoon.dev/171401)

2022-06-27 06:49 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-06-27 23:47 UTC, merged