close #24 RasPi環境でデータファイルを読み込む
KatLab-MiyazakiUniv/etrobocon2022 pull request #32
Opened 2022-06-26 09:35 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- GameMotionParserクラスを追加(GameMotionParser.h, GameMotionParser.cpp)
- Motion/GameMotionを追加
- Motion/GameMotion下のファイルをビルド対象としてMakefileに追記

# 動作テスト
## 実験方法
カメラシステムから送信したディレクトリ内のファイルを、実機で読み込みprintfで表示できることを確認する。

## 実験結果
送信したファイルの内容を出力できた。

## 添付資料

2022-06-26 19:57 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-06-27 01:04 UTC, mutotaka0426 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
Motionの中にGameMotionがあるのおかしくない？
どちらかというと逆な気がする

ていうかMotionとGameMotionは同じところに置いてもいいのでは？
あくまでパッケージ分けしてるだけでしょ？

2022-06-27 01:13 UTC, mutotaka0426 requested changes
ファイル読み込み出来てるみたいだし基本は大丈夫そう
一部気になったところだけ

2022-06-27 01:13 UTC, mutotaka0426 commented on .gitignore
> +
なんでgitから外してるの？

たぶん送信される前からファイル自体は置くと思うけど，そのファイルは追跡できた方がよくない？

2022-06-27 01:13 UTC, mutotaka0426 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
Motionの中にGameMotionがあるのおかしくない？
どちらかというと逆な気がする

ていうかMotionとGameMotionは同じところに置いてもいいのでは？
あくまでパッケージ分けしてるだけだし

2022-06-27 01:41 UTC, miyashita64 commented on .gitignore
> +
後々、カメラシステムからデータを受け取るたびに変更されるので、それが変更としてコミットに挙がるのはよくないと思い除外しました。

2022-06-27 01:42 UTC, miyashita64 commented on .gitignore
> +
必要になったファイルは適宜除外しないよう設定すれば良いとお思っています。

2022-06-27 01:51 UTC, miyashita64 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
moduleが、Motion（動作系）とAPI（呼び出し）に分かれているので、GameMotionはMotionの下位だと思います。
必ずしも分ける必要はないかもしれませんが、混ぜるメリットもあまり思いつかないので、分けた方がわかりやすいと思います。

2022-06-27 04:32 UTC, miyashita64 commented on .gitignore
> +
ご指摘の意図とは違うと思いますが、

`transfer_data/*`

と書いているつもりでした。修正しました。

2022-06-27 11:53 UTC, mutotaka0426 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
ごめん分かりづらい言い方したわ
MotionとGameMotionを同じところっていうのは，混ぜるって意味じゃなくて２つともmodule下に置いていいんじゃないってこと
- module/Motion/
- module/GameMotion/
 
パッケージの中にパッケージってわかりづらくない？
それともMotionって動作系全般を置くパッケージって意味だったの？てっきり直進とか回頭とかの汎用動作をまとめるパッケージだと思ってたんだけど

2022-06-28 12:18 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/171819)

2022-06-29 01:08 UTC, kodama0720 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
MotionとGameMotionは内容的には並列でいいと思いますが、名前的にはMotionがGameMotionを包含しているように感じられます。
このチケットで変更するかはお任せしますが、Motionの名前を変更した方がいいと思います。

2022-06-29 04:08 UTC, miyashita64 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
MotionがBasicMotionなら違和感はない？

2022-06-29 06:42 UTC, kodama0720 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
何か若干名前に違和感があるような気がするけど、代案思いつかないし僕はそれがいいと思う

2022-06-29 11:52 UTC, mutotaka0426 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
GameMotionはMotionからなるわけだから，今のままの名前でも良さそうじゃない？
継承の名前の付け方みたいでいい感じだと思うけどダメかな？

2022-06-30 01:39 UTC, kodama0720 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/module/Motion/GameMotion)
確かに関連性を考えるといいような気がしてきました

2022-06-30 03:55 UTC, sugaken0528 approved these changes
![LGTM](https://image.lgtmoon.dev/172076)

2022-06-30 04:05 UTC, mutotaka0426 commented
俺のチケットでEtRobocon2022.cppいじってたからコンフリクト起きてるね
mainプルしたら解決するかな

2022-06-30 04:33 UTC, merged