close #26 ライトレースエリアを攻略する
KatLab-MiyazakiUniv/etrobocon2022 pull request #34
Opened 2022-06-27 00:10 UTC by mutotaka0426

# チェックリスト

- [x] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- ライントレースをするLineTracerクラスを追加
- ライントレースエリアを攻略するLineTraceAreaクラスを追加
- ダミーのColorSensor::getBrightness()で白と黒の値を交互に返すように変更
- EtRobocon2022.cppにライントレースエリアを攻略する処理を追加

# 動作テスト
実機でLコースを10回走らせた
- ゴール率: 10/10
- 走行タイム: 約20秒

# 問題点
- ゴール後の緑のマーカーで止まる処理がかなり不安定
- 白と黒の間を緑と認識してしまうので，色識別クラスの精度を向上する必要がある

2022-06-28 13:06 UTC, sugaken0528 requested changes
動作系のプルリクには動画も載せてくれるとありがたい

2022-06-28 13:06 UTC, sugaken0528 commented on module/LineTraceArea.cpp
> +        SectionParam{ 485 + 250, 45, 50, PidGain(1.2, 0.8, 0.8) } };
targetBrightnessって走行中変えたいことあるかな?
毎年同じ目標輝度指定して走ってるからLineTracerが定数として持ってても良い気がするけど。

2022-06-28 13:24 UTC, miyashita64 reviewed
いいと思います。
小さいことをいくつかコメントしましたが、気にならなければ大丈夫です。

2022-06-28 13:24 UTC, miyashita64 commented on module/EtRobocon2022.cpp
> +  LineTraceArea::runLineTraceArea(isLeftCourse);
この関数名が`run`でないのは、クラス名が動作ではないからですか？

2022-06-28 13:24 UTC, miyashita64 commented on module/LineTraceArea.h
> +   * @fn static void runLineTraceArea();
リポジトリ全体で@fnがあるものとないものが混在しているので統一した方がいいと思いますが、必要ですかね？

2022-06-28 13:24 UTC, miyashita64 commented on module/Motion/LineTracer.cpp
> +  while(colorCount < 3) {
3は定数で持った方がいいと思います。

2022-06-28 13:43 UTC, mutotaka0426 commented on module/EtRobocon2022.cpp
> +  LineTraceArea::runLineTraceArea(isLeftCourse);
そうだね
クラス名が動名詞とかだったらrunで伝わるかなって思うけど，LineTraceAreaクラスでrunだけだと伝わりづらいかなって思ってこうしてる

2022-06-28 13:44 UTC, mutotaka0426 commented on module/LineTraceArea.cpp
> +        SectionParam{ 485 + 250, 45, 50, PidGain(1.2, 0.8, 0.8) } };
多分キャリブレーションのときに黒と白の輝度を取得して決定するよね
そう考えたら引数の方がいいかも

2022-06-28 21:19 UTC, Takahiro55555 approved these changes
コメントした部分以外では、新たに気になる点は見つけられませんでした

2022-06-29 00:53 UTC, kodama0720 reviewed
特に大きな修正点は見当たりませんでした。

2022-06-29 00:56 UTC, kodama0720 commented on module/LineTraceArea.cpp
> +        SectionParam{ 0, 50, PidGain(1.0, 1.0, 1.0) } };
LコースとRコースでフォーマットをそろえた方が見やすいかと思います。
ただ、clang-formatの仕様だとするとこのままでもいい気もします。

2022-06-29 04:28 UTC, mutotaka0426 commented on module/LineTraceArea.cpp
> +        SectionParam{ 0, 50, PidGain(1.0, 1.0, 1.0) } };
これclang-formatで勝手になるから，変数名の文字数を無理やり合わせるとかしないと揃わないね

2022-06-29 13:20 UTC, sugaken0528 approved these changes
LGTM

2022-06-29 13:50 UTC, kodama0720 approved these changes
LGTM!

2022-06-29 13:50 UTC, merged