add: キャリブレーションを行う処理の実装
KatLab-MiyazakiUniv/etrobocon2022 pull request #48
Opened 2022-07-06 21:39 UTC by mutotaka0426

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- キャリブレーション処理を行うCalibratorクラスを追加
- Calibratorクラスのテストコードを追加
- 本実装に伴って超音波センサと走行体ボタンのテストダミーを追加

# キャリブレーションからスタートまでの流れ
1. 走行システムを起動する
2. コースを選択する
  a) `Select a Course`の文字が出力される
  b) 走行体の左右ボタンを押してLRを選択する（正面から見て左がL，右がR）
  c) 中央ボタンを押してコースを確定する
3. 目標輝度を測定する
  a) "Press the Center Button on the Black"が出力される
  b) カラーセンサが黒の上になるように走行体を置いて中央ボタンを押す
  c) 取得した黒の輝度が出力される
  d) "Press the Center Button on the White"が出力される
  e) カラーセンサが白の上になるように走行体を置いて中央ボタンを押す
  f) 取得した白の輝度が出力される
  g) 目標輝度が出力される
4. 走行体をスタート位置にセットして待機させる
5. 超音波センサの前に手を置いてスタート合図を送る

# 動作テスト
実際に走らせた時の動画
体験版の編集ソフト使ったので画質が悪いのは許してください

https://user-images.githubusercontent.com/56989154/177644251-03438c13-18b7-43ad-bf95-42365a6144cc.mp4

2022-07-09 08:04 UTC, Takahiro55555 requested changes
ほぼ修正すべき箇所のない良いコードだと思います。
一部気になる箇所をコメントしました。
確認いただければ幸いです。

2022-07-09 08:04 UTC, Takahiro55555 commented on test/dummy/ev3api_button.cpp
> +  }
このコードが必要な理由がよく分かりませんでした...
`num = rand() % 3`を実行していることから、この部分のコードは絶対に実行されないように見えたのですが、必要な理由等があれば教えていただけると幸いです。

2022-07-09 17:09 UTC, mutotaka0426 commented on test/dummy/ev3api_button.cpp
> +  }
`button`に左ボタン，右ボタン，中央ボタン以外が指定されてしまっているときに，エラー文を出そうと思って記述しているんだけど間違ってる？

コメントを付けてなかったので追加しておきます

2022-07-09 17:57 UTC, Takahiro55555 commented on test/dummy/ev3api_button.cpp
> +  }
ごめん、引数(`button`)のほうを見逃してました...

2022-07-10 13:18 UTC, miyashita64 requested changes
コメントミスがあったので、その修正をお願いします。
関数名等は個人差だと思うので、判断はお任せします。

2022-07-10 13:18 UTC, miyashita64 commented on module/EtRobocon2022.h
> +#include "SystemInfo.h"
EtRobocon2022については、.hでincludeするとエラーになる場合があるので、現状.cpp側でincludeしていると思うので合わせた方がいいのではないでしょうか。

2022-07-11 16:29 UTC, Takahiro55555 approved these changes
@miyashita64 が指摘している点以外は、大丈夫だと思います。

LGTM!!!

```
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢀⠋⢐⣧⠤⠤⠤⠤⣀⢀⡤⠲⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢀⣡⠋⡀⡀⡀⡀⡀⡀⡀⡀⠑⡄⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡿⡀⡀⡀⡀⡀⡄⡀⡀⡀⡀⡀⡀⣇⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⣀⣀⣀⡀⡀⡀⡀⡀⣀⠃⡀⡀⡀⡀⠩⠏⡀⡀⡀⡀⡀⡀⢸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⠲⠲⣿⣒⠂⣄⣾⡀⡴⢠⢩⢩⣹⢹⢩⠙⢛⢲⣲⠒⠒⠒⠚⣤⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⠉⠈⠁⠶⠶⠁⠧⢠⠠⠂⠁⠘⠿⠤⠚⠠⡀⠻⣿⣀⣠⠤⠤⠈⡴⢋⡉⡛⢦⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢸⠉⡀⢀⡍⠙⡄⡀⣠⡀⡀⢦⣃⣀⣐⡊⢸⠠⠡⣉⣀⡀⠙⣤⣀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠘⡀⢔⡘⠉⡀⠈⠒⡄⡀⣹⠁⡀⢸⠐⠪⢸⡀⣼⠁⠈⣧⡀⡀⡀⣧⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⣏⠉⠁⡀⠈⡌⣤⠑⡄⡀⡀⡀⠙⢦⠃⡀⡀⣸⡨⢁⠇⠤⡀⣇⡀⢧⢀⡀⡀⡿⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⣇⡀⡀⡀⠙⢦⢯⠷⣄⡀⡀⡀⡀⡀⡀⡀⣁⠞⡁⠂⡀⠅⢸⡀⡀⠉⠛⠉⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⠈⠓⠶⠶⣀⠋⡀⠈⠄⢈⡽⢉⡉⣉⠭⠥⠒⠉⢺⢆⡀⢀⡀⡆⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⠛⠋⡀⣷⢐⡞⡀⡀⡀⡀⡀⡀⢑⡀⠠⡀⡇⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢀⣀⣀⡀⡟⢐⡀⡀⡀⡀⡀⡀⡀⡂⡀⠠⡀⠁⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡞⣔⡐⠄⢀⠄⢸⡀⡀⡀⡀⡀⡀⡀⡑⡀⡐⢸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢷⢣⢄⢀⡀⡀⠐⡄⡀⡀⡀⡀⡀⢠⠤⡃⡨⡿⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢦⠓⠼⢸⠉⠛⠶⢤⣄⣀⡀⠠⠃⠂⢑⢡⠁⠈⢦⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢛⠄⡀⡀⢹⡀⡀⡀⡀⡀⢸⠸⣥⠃⡟⠳⣄⠂⠈⢦⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡏⡀⡀⡀⡾⡀⡀⡀⡀⡀⣸⡀⡀⣼⡀⡀⡀⠓⣜⠋⠈⢦⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠛⠶⠖⠉⡀⡀⡀⡀⡀⡀⡇⡀⡀⢷⡀⡀⡀⡀⡀⠳⣄⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢷⡀⡀⠈⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⠶⠞⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
```

2022-07-12 11:43 UTC, kodama0720 reviewed
処理に問題はないように思います。

2022-07-12 11:43 UTC, kodama0720 commented on test/dummy/ev3api_button.cpp
> +  // 中央ボタンが押された時（num=0）
num=2ですか？

2022-07-13 02:46 UTC, miyashita64 approved these changes
LGTM!!

2022-07-13 02:48 UTC, sugaken0528 requested changes
Logメソッドをprintで代用してるとこTODOコメントしといた方が良きじゃ?

2022-07-13 04:22 UTC, mutotaka0426 commented
> Logメソッドをprintで代用してるとこTODOコメントしといた方が良きじゃ?

loggerを取り込んで動くことは確認してるから，loggerがマージされたらプッシュします

2022-07-13 13:26 UTC, mutotaka0426 commented
手元環境壊れたちょっと待ってください

2022-07-14 05:41 UTC, sugaken0528 approved these changes
LGTM

2022-07-14 05:59 UTC, merged