色識別の精度を上げる
KatLab-MiyazakiUniv/etrobocon2022 pull request #49
Opened 2022-07-07 04:53 UTC by miyashita64

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- コードの変更は現状なし

# やったこと
- RGB値の測定
- 現状の色識別精度を確認
- 色識別の閾値調整ツール作成

# 動作テスト

## 実験方法
- 実験1. ライントレースエリアゴール後からライントレースしながらRGB値を計測
- 実験2. 各色のカラーマーカーについて四方からRGB値を計測
- 実験3. ゲームエリア上の経路を横断(手押し)しながらRGB値を計測

## 実験データ
- 上の図は計測値、下の図は識別した色
- 下の図に紛れている縦線の色は計測値の色
- 縦線が目立つ箇所は、計測値と識別した色との差が大きいため、誤識別である可能性が高い

### 実験1. ライントレースエリアゴール後からライントレースしながらRGB値を計測
- 青線を識別できていない
- ラインを緑、まれに黄と誤識別している箇所がある
- ライントレースのためラインを白と判定しているのは問題ない？

![image](https://user-images.githubusercontent.com/83441177/177692887-5e983e00-12cc-40f4-93ec-b91632068f69.png)

### 実験2. 各色のカラーマーカーについて四方からRGB値を計測
- 緑と青は識別できている
- 赤と黄は白と誤識別している

![image](https://user-images.githubusercontent.com/83441177/177692380-678cfa04-6299-495a-aea6-70de86844fd2.png)

### 実験3. ゲームエリア上の経路を横断(手押し)しながらRGB値を計測
- 黒を緑と識別している箇所がある
- 赤と黄をほとんど識別できていない

![image](https://user-images.githubusercontent.com/83441177/177691989-9b45c11f-026f-45b6-80dd-19b069b500b0.png)

## 実験結果
以下のパターンで誤識別が発生している
- 黒 -> 緑、まれに黄
- 青 -> 白
- 赤、黄 -> 白

## 添付資料

2022-07-10 18:01 UTC, mutotaka0426 requested changes
行き過ぎる問題とかは色々と要改善だろうけど，色識別の精度自体は結構いい感じだと思う
LineTracer::runToColorの`JUDGE_COUNT`を1とかにしたら流石に変なところで止まってしまうかな？
まぁ3→1にしたところでそんな変わらないか

テストコードを綺麗に整理してくれてありがとう！
小さい指摘だけしてるの対応お願いします

2022-07-10 20:26 UTC, mutotaka0426 commented on test/test_data/RgbData.h
> +static constexpr rgb_raw_t BLUE_DATA[] = {
いや，明示するって意味では書いた方がいい気がしてきた

2022-07-11 08:49 UTC, Takahiro55555 approved these changes
@mutotaka0426 が指摘した部分以外で気になる点は無かったです

2022-07-11 13:28 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/141681)

2022-07-12 02:47 UTC, sugaken0528 approved these changes
お疲れ様です

2022-07-12 12:10 UTC, merged