Ticket 41
KatLab-MiyazakiUniv/etrobocon2022 pull request #50
Opened 2022-07-10 03:36 UTC by sap2368

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- commonディレクトリを作成しその直下にLogging.cppとLogging.hを作成した
# 動作テスト
- EtRobocon2022.cppに```
  Logging logging;
  logging.writeWarnings("The pwm value passed to StraightRunner::run is 0");
```を書き加え`./make.sh sim up`実行後にThe pwm value passed to StraightRunner::run is 0と黄色文字で表示されるのを確認した。
## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2022-07-10 05:32 UTC, mutotaka0426 commented on common/Logging.h
> +  void writeErrors(const char* errors);
各関数には必ずコメントを付けてください

2022-07-10 06:03 UTC, mutotaka0426 requested changes
テストコードも一応書いてほしいです
アサーションを使わない，出力を確認するだけのテストでいいから，正しく実装できていることが確認できるようにお願いします

あと，可読性を考慮したコーディングを心掛けてほしいです
可読性が低いと開発効率が落ちるし，来年以降の人たちが見たときにも困るので，誰が見てもわかるようなコードにするようによろしくお願いします

2022-07-10 07:08 UTC, Takahiro55555 commented on Makefile.inc
> +                     sed -r 's/(\/.*)*\/(.*\.)cpp/\2o/g'`)
以前自分が @sap2368 と`common`の話をしたときは、`common`をプロジェクトルート直下に置くのではなく、`module/Common`のように、`module`ディレクトリの中に置くことを想定していました。

`module`ディレクトリの中ではなく、プロジェクトルートに`common`を置いた理由等を教えていただければ幸いです。

2022-07-10 07:10 UTC, sap2368 commented on Makefile.inc
> +                     sed -r 's/(\/.*)*\/(.*\.)cpp/\2o/g'`)
完全に私の勘違いでした変更します

2022-07-10 07:14 UTC, Takahiro55555 commented on Makefile.inc
> +                     sed -r 's/(\/.*)*\/(.*\.)cpp/\2o/g'`)
すみません m(_ _)m

よろしくお願いします。

2022-07-10 13:33 UTC, miyashita64 requested changes
ドキュメントコメントの修正をお願いします。

2022-07-10 13:33 UTC, miyashita64 commented on module/common/Logging.cpp
> + * @file Logging.h
```suggestion
 * @file Logging.cpp
```

2022-07-10 17:17 UTC, mutotaka0426 requested changes
いくつか気になった点があるので修正お願いします

前のチェンジリクエストでも書いたけど，渡された文字列を緑色でそのまま表示するやつも欲しいです

2022-07-10 17:17 UTC, mutotaka0426 commented on module/Motion/StraightRunner.h
> -
間違えてコミットした？

2022-07-10 17:17 UTC, mutotaka0426 commented on module/common/Logging.h
> +  void writeLogs(const char* logs);
コメント書いてとしか言わなかったけど，他のファイルみたいにdoxygen形式のコメントで書いてほしい．他の関数も同様で

あと，他は変更したけどここは複数形（logs）なのはなんで？修正忘れ？

```suggestion
  /**
  ** 入力された文字列をLogとしてターミナルに表示
  ** @param logs
  **/
  void writeLogs(const char* logs);
```

2022-07-10 17:17 UTC, mutotaka0426 commented on module/common/Logging.h
> +  char* Logs;
後から機能拡張するときに分からなくなるからコメントを追記しておいてください

```suggestion
  char* Logs; // システムのログを保持する
```

2022-07-10 19:16 UTC, mutotaka0426 commented on module/common/Logging.h
> +  **/
すみません，説明不足でした．
- 最初の行の*以外は一つでいい
- 「@param 変数名 変数の説明」の形で書く
- ヘッダファイルに書いてある他の関数宣言においても同様
- [参考記事](https://qiita.com/inabe49/items/23e615649e8539d857a8)

他のクラスのヘッダファイルを参考にするといいと思います．なんならコピペして書き換えるの方が確実かもしれないです．

```suggestion
  /**
  * 入力された文字列をLogとしてターミナルに表示
  * @param logMessage 表示するLogメッセージ
  */
```

2022-07-10 19:49 UTC, mutotaka0426 commented on module/Motion/StraightRunner.h
> -
間違えて行を消したのをコミットしたのであれば，戻しておいてください

2022-07-11 04:12 UTC, kodama0720 commented on module/common/Logging.cpp
> +void Logging::writeLogMessage(const char* logMessage)
writeってファイル書き込みっぽさがあるからprintLogMessageとかの方がいいかも？
（今後ファイル書き込みもするつもりなんだっけ？）

2022-07-11 08:36 UTC, mutotaka0426 commented on module/common/Logging.cpp
> +void Logging::writeLogMessage(const char* logMessage)
log（動詞）でもいいんじゃない？
- Logging::log()
- Logging::logWarning()
- Logging::logError()
- Logging::logHighlight()
とか？

2022-07-11 08:38 UTC, mutotaka0426 commented
クラス名としてはLoggerの方が適切な気がしてきた
@Takahiro55555 が確か発案してたけど，PythonのLoggingライブラリから名前取ってったんだっけ？

2022-07-11 10:48 UTC, sap2368 commented on module/Motion/StraightRunner.h
> -
Logging.hを加えてstraightrunnerでも動くことを確認して消しました

2022-07-11 13:21 UTC, mutotaka0426 commented on module/Motion/StraightRunner.h
> -
そうじゃなくて多分空行を消してしまってるんだと思うんだけど
StraightRunnerで試した時に，もともとあった空行まで消してしまって，そのままコミットしちゃったんじゃないの？
そうでなければ，Files ChangedにStraightRunnerの変更は出てこないよ

2022-07-11 13:50 UTC, mutotaka0426 approved these changes
お疲れ様です！
![LGTM](https://image.lgtmoon.dev/119810)

2022-07-11 15:50 UTC, Takahiro55555 commented on test/LoggingTest.cpp
> +  }
```suggestion
  TEST(LoggerTest, writeLogs)
  {
    Logger logger;
    std::string logMsg = "logs test.";
    std::string expected = logMsg + "\n";

    testing::internal::CaptureStdout(); // 標準出力キャプチャ開始
    logger.log(logMsg.c_str());
    std::string actual = testing::internal::GetCapturedStdout(); // キャプチャ終了

    ASSERT_STREQ(expected.c_str(), actual.c_str());
  }

  TEST(LoggingTest, writeWarningMessage)
  {
    Logger logger;
    std::string logMsg = "WarningMessage test.";
    std::string expected = "\x1b[36m";  // 文字色をシアンに
    expected += "Warning: " + logMsg + "\n";
    expected += "\x1b[39m";  // 文字色をデフォルトに戻す

    testing::internal::CaptureStdout(); // 標準出力キャプチャ開始
    logger.logWarning(logMsg.c_str());
    std::string actual = testing::internal::GetCapturedStdout(); // キャプチャ終了

    ASSERT_STREQ(expected.c_str(), actual.c_str());
  }
```

2022-07-11 16:41 UTC, Takahiro55555 commented
素早い対応ありがとうございます。
そしてお疲れ様です！

LGTM!!!
```
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣠⠋⣆⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡞⢀⡥⠚⠛⠉⠉⠉⠙⠒⠤⣖⠩⢽⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⠄⣛⣛⣻⢀⣀⡀⡀⣤⡀⡀⡀⠄⣞⠞⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⣼⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⠦⠤⠟⠰⠶⢠⠃⡏⡀⡀⡀⢠⠃⡀⡀⡀⡀⡀⢴⡀⡀⡀⡀⡀⡀⡀⠈⡄⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⠈⠉⠉⡀⠁⡀⡀⡀⣸⡀⡀⡀⡀⡀⠈⣿⠉⡀⡀⡀⡀⡀⡀⡀⣿⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⣭⣭⣽⠠⣤⡀⡀⢰⡀⠉⠏⠉⠛⢛⢲⡲⠒⠶⠶⠶⢤⢤⡤⣤⣤⣤⣹⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⠒⠒⠚⠘⠛⢠⠋⡞⡀⡾⢐⠠⠚⢿⣺⡀⡇⡀⡀⠈⣿⢸⡀⡿⠐⠈⠆⠈⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢀⡤⠶⠶⣤⣐⡀⡀⡀⠉⡀⡀⠉⢷⢛⣉⡀⡀⢀⠁⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠩⣂⠈⣁⣤⠳⡀⢀⠟⣤⡀⣩⠓⠒⠒⠶⠐⢸⢦⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣀⣀⣀⢧⠂⠥⢸⡀⡀⡀⠈⠹⡀⠄⣼⡀⡀⡀⣇⠠⣀⣸⡀⠙⡄⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⢼⡁⡀⡀⡀⡀⢧⠳⣌⠃⠄⡀⡀⡀⡀⠙⣤⡁⡀⡀⡀⠇⠐⣠⠋⢂⢠⠸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⠸⡀⡀⡀⡀⠈⠦⡀⣉⣶⣀⢸⡉⠉⡀⡀⠈⣧⡀⠞⣨⠞⢁⡄⢀⡀⡏⣧⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⢤⣀⣤⡀⡀⢒⠢⠠⠂⡉⢛⡀⡀⡀⡀⠘⢯⡉⡀⡴⠁⡀⡐⢠⠁⢹⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠈⠙⠲⣬⣤⡥⠚⢹⠙⣄⣀⣄⡀⢀⢒⡠⢈⡀⠘⣠⠋⢂⢸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢥⡀⡀⠈⠛⠶⣤⣥⡴⢋⢀⡀⡀⢸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣀⣤⠤⠤⣤⡾⢀⢯⡀⡀⡀⡀⡀⡀⡀⡀⠌⡀⡀⡀⣿⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢸⡀⠑⠄⡀⡔⠠⡀⢿⡀⡀⡀⡀⡀⡀⡀⡀⡀⢀⠐⡀⡇⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠈⡄⢠⡌⡀⡀⡀⡀⠜⡀⡀⡀⡀⡀⡀⡀⣸⠆⡀⢌⢠⢦⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⡀⠴⣴⠸⡉⠙⠲⢦⣄⣀⡀⡀⡀⡠⠣⠨⢀⡝⡾⠠⠙⣄⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠈⢦⡀⡀⠉⠛⣄⡀⡀⡀⠈⠉⠉⢻⢠⠄⡾⢰⠓⣄⠑⠔⠙⢄⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡾⡀⡀⡀⡀⡟⡀⡀⡀⡀⡀⡀⢸⡀⠈⢀⠏⡀⡀⠙⣌⢔⣢⠙⣄⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣇⡀⡀⣠⠞⡀⡀⡀⡀⡀⡀⢠⠋⡀⡀⡞⡀⡀⡀⡀⡀⠑⣄⡀⡀⢧⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠉⠉⡀⡀⡀⡀⡀⡀⡀⡀⢸⡀⡀⡀⠘⡀⡀⡀⡀⡀⡀⡀⠑⣤⡼⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢷⡀⡀⡀⡇⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⠲⠞⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
```

2022-07-11 16:42 UTC, Takahiro55555 approved these changes
素早い対応ありがとうございます。
そしてお疲れ様です！

LGTM!!!
```
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣠⠋⣆⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡞⢀⡥⠚⠛⠉⠉⠉⠙⠒⠤⣖⠩⢽⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⠄⣛⣛⣻⢀⣀⡀⡀⣤⡀⡀⡀⠄⣞⠞⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⣼⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⠦⠤⠟⠰⠶⢠⠃⡏⡀⡀⡀⢠⠃⡀⡀⡀⡀⡀⢴⡀⡀⡀⡀⡀⡀⡀⠈⡄⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⠈⠉⠉⡀⠁⡀⡀⡀⣸⡀⡀⡀⡀⡀⠈⣿⠉⡀⡀⡀⡀⡀⡀⡀⣿⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⣭⣭⣽⠠⣤⡀⡀⢰⡀⠉⠏⠉⠛⢛⢲⡲⠒⠶⠶⠶⢤⢤⡤⣤⣤⣤⣹⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⠒⠒⠚⠘⠛⢠⠋⡞⡀⡾⢐⠠⠚⢿⣺⡀⡇⡀⡀⠈⣿⢸⡀⡿⠐⠈⠆⠈⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢀⡤⠶⠶⣤⣐⡀⡀⡀⠉⡀⡀⠉⢷⢛⣉⡀⡀⢀⠁⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠩⣂⠈⣁⣤⠳⡀⢀⠟⣤⡀⣩⠓⠒⠒⠶⠐⢸⢦⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣀⣀⣀⢧⠂⠥⢸⡀⡀⡀⠈⠹⡀⠄⣼⡀⡀⡀⣇⠠⣀⣸⡀⠙⡄⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⢼⡁⡀⡀⡀⡀⢧⠳⣌⠃⠄⡀⡀⡀⡀⠙⣤⡁⡀⡀⡀⠇⠐⣠⠋⢂⢠⠸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⠸⡀⡀⡀⡀⠈⠦⡀⣉⣶⣀⢸⡉⠉⡀⡀⠈⣧⡀⠞⣨⠞⢁⡄⢀⡀⡏⣧⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⢤⣀⣤⡀⡀⢒⠢⠠⠂⡉⢛⡀⡀⡀⡀⠘⢯⡉⡀⡴⠁⡀⡐⢠⠁⢹⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠈⠙⠲⣬⣤⡥⠚⢹⠙⣄⣀⣄⡀⢀⢒⡠⢈⡀⠘⣠⠋⢂⢸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢥⡀⡀⠈⠛⠶⣤⣥⡴⢋⢀⡀⡀⢸⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣀⣤⠤⠤⣤⡾⢀⢯⡀⡀⡀⡀⡀⡀⡀⡀⠌⡀⡀⡀⣿⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢸⡀⠑⠄⡀⡔⠠⡀⢿⡀⡀⡀⡀⡀⡀⡀⡀⡀⢀⠐⡀⡇⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠈⡄⢠⡌⡀⡀⡀⡀⠜⡀⡀⡀⡀⡀⡀⡀⣸⠆⡀⢌⢠⢦⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⡀⠴⣴⠸⡉⠙⠲⢦⣄⣀⡀⡀⡀⡠⠣⠨⢀⡝⡾⠠⠙⣄⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠈⢦⡀⡀⠉⠛⣄⡀⡀⡀⠈⠉⠉⢻⢠⠄⡾⢰⠓⣄⠑⠔⠙⢄⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡾⡀⡀⡀⡀⡟⡀⡀⡀⡀⡀⡀⢸⡀⠈⢀⠏⡀⡀⠙⣌⢔⣢⠙⣄⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⣇⡀⡀⣠⠞⡀⡀⡀⡀⡀⡀⢠⠋⡀⡀⡞⡀⡀⡀⡀⡀⠑⣄⡀⡀⢧⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠉⠉⡀⡀⡀⡀⡀⡀⡀⡀⢸⡀⡀⡀⠘⡀⡀⡀⡀⡀⡀⡀⠑⣤⡼⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⢷⡀⡀⡀⡇⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⠙⠲⠞⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀⡀
```

2022-07-11 16:43 UTC, mutotaka0426 requested changes
名前の変更し忘れがあったので修正お願いします

2022-07-11 16:43 UTC, mutotaka0426 commented on module/common/Logger.h
> + * @file Logging.h
```suggestion
 * @file Logger.h
```

2022-07-11 16:43 UTC, mutotaka0426 commented on module/common/Logging.cpp
> + * @file Logging.cpp
ファイル名も`Logging.cpp`のままだから，`Logger.cpp`に直しておいて
```suggestion
 * @file Logger.cpp
```

2022-07-11 16:43 UTC, mutotaka0426 commented on test/LoggerTest.cpp
> +  TEST(LoggingTest, writeErrorMessage)
```suggestion
  TEST(LoggerTest, writeErrorMessage)
```

2022-07-11 16:43 UTC, mutotaka0426 commented on test/LoggerTest.cpp
> +  TEST(LoggingTest, writeHighlightLog)
```suggestion
  TEST(LoggerTest, writeHighlightLog)
```

2022-07-11 16:45 UTC, mutotaka0426 commented on test/LoggerTest.cpp
> +  TEST(LoggerTest, writeLogs)
ここもだ
```suggestion
  TEST(LoggerTest, log)
```

2022-07-12 02:27 UTC, sugaken0528 requested changes
他の動作クラスでWarningをPrintfで出力している部分があるのでそこの修正もお願いします

2022-07-12 12:23 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/173692)

2022-07-13 02:19 UTC, sugaken0528 requested changes

2022-07-13 02:19 UTC, sugaken0528 commented on module/Motion/LineTracer.cpp
> +  Logger logger;
メソッド毎にインスタンス化じゃなくてクラス毎にインスタンス化で良いと思う。
つまりヘッダに記述した方が良いと思う。

2022-07-13 04:12 UTC, sugaken0528 approved these changes
LGTM!!
お疲れさん

2022-07-13 06:45 UTC, miyashita64 approved these changes
LGTM!!

2022-07-13 06:56 UTC, miyashita64 commented
CMakeLists.txtでコンフリクトが起きてるようなので、
1. `git pull origin main`
2. Ctrl + X でExit
3. CMakeLists.txtのコンフリクトを解決（このチケットで追加した部分と[別チケット](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/pull/49/files)で追加した部分をどちらも残してください）

2022-07-13 07:59 UTC, merged