close #37 ボーナスブロックの設置
KatLab-MiyazakiUniv/etrobocon2022 pull request #51
Opened 2022-07-10 10:12 UTC by sugaken0528

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- BonusBlockCarrierクラスを追加
- 直進クラスに左右のモーターカウントの誤差を補正する処理を追加
- 旋回クラスにおいて徐々に旋回スピードを遅くする処理を削除

# 動作テスト
実機においてボーナスブロック設置動作を20回行った

## 実験方法

## 実験データ

## 実験結果
ボーナスブロック設置の成功率50％(10/20)

## 添付資料
- 成功例
https://user-images.githubusercontent.com/62526141/178140424-c0a457ba-0768-41b1-857b-824f617e1150.MOV
- 失敗例1(エッジを認識できなかった)
https://user-images.githubusercontent.com/62526141/178140477-6cdab8db-72d9-4270-9789-0e027914d38a.MOV
- 失敗例2(直進が大きく逸れた)
https://user-images.githubusercontent.com/62526141/178140510-faa9312b-a3c9-4bee-9c8b-19cc0a680b52.MOV

2022-07-10 18:54 UTC, mutotaka0426 requested changes
処理の流れについては文句ないです
ほとんどは名前の付け方やコメントの仕方について指摘しているので対応お願いします

あと，回帰テストにもなるからBonusBlockCarrierについてもテストしてほしいです
ただ呼び出すだけのテストでも大丈夫だと思います

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.cpp
> +  int targetBrightness = (93 - 3) / 2;  // 目標輝度
目標輝度はキャリブレータが計測したものを渡すはずだから，引数とかにしておいてほしい

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.cpp
> +
ここからの処理は下のブロックサークルエリアに置く処理だよね？
その旨をコメントに書いてほしい

多分この関数を拡張して，4パターン（上下左右）の設置動作に分岐するのかな？
だとしたら，そのこともコメントしておいてほしい（上左右は未実装的なコメント）
TODOリストをコメントとして書いてもいいと思う

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.h
> +  static void carryBonusBlock();
他のクラスのヘッダと同様にコメントを残しておいてほしい

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.h
> +};
staticクラスにするなら，privateにコンストラクタを記述してインスタンス化を禁止してほしい

参考：[資料](https://programming-place.net/ppp/contents/cpp/language/018.html)の`staticクラス`の項目

```suggestion
 private:
  BounusBlockCarrier(); // インスタンス化を禁止する
};
```

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.cpp
> +void BonusBlockCarrier::carryBonusBlock()
クラス名で何をするのか分かるし，`run`の方が楽でよくない？
関数を複数個に分ける想定ならこのままでもいいけど，分けるとしてもLRだけかな？
その場合は`runLeft`とか`runLeftCourse`とか？
```suggestion
void BonusBlockCarrier::run()
```

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.cpp
> +  // 緑を認識するまで直進(指定した距離まで直進で代用)
`TODO: ~`って形でコメントしとけば，後で検索もできるしいいかも
```suggestion
  // 緑を認識するまで直進
  // TODO: 指定した距離まで直進で代用してるので，指定した色まで直進に変更する
```

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.cpp
> +  // 緑を認識するまでライントレース(指定した距離までライントレースで代用)
同上

2022-07-10 18:54 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.cpp
> +  // 左に80度回頭
来年以降のためにも，プルリクの変更点で書いてるようなことをコメントしてあげた方がいいと思う
回頭を分けてる理由について

2022-07-12 04:53 UTC, Takahiro55555 approved these changes
@mutotaka0426 の指摘した点以外は大丈夫だと思います。

2022-07-12 12:08 UTC, kodama0720 reviewed
動作は良いと思います

2022-07-12 12:08 UTC, kodama0720 commented on test/RotationTest.cpp
>      // 90度左回頭の回頭誤差が１度未満かテスト
```suggestion
    // 90度左回頭の回頭誤差が3度未満かテスト
```

それと、できれば許容する誤差の説明が欲しいです

2022-07-12 20:40 UTC, sugaken0528 commented on module/Motion/BonusBlockCarrier.cpp
> +
1個の関数でやるより上下左右で関数分けした方が良いかな?

2022-07-13 03:26 UTC, kodama0720 approved these changes
LGTM!

2022-07-13 09:12 UTC, mutotaka0426 commented on module/Motion/BonusBlockCarrier.cpp
> +  // 90度回頭の間に後退を行うことによって設置を行う
```suggestion
  /** 
  * そのまま90度回頭して設置するとブロックがベースエリアからはみ出る場合があるため，
  * 回頭と後退を分けて実行する
  */   
```

2022-07-13 13:37 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/173802)

2022-07-13 14:16 UTC, mutotaka0426 requested changes
気になったところあったので，対応お願いします

2022-07-13 14:16 UTC, mutotaka0426 commented on test/BonusBlockCarrierTest.cpp
> +#include "Controller.h"
これいるの？
```suggestion

```

2022-07-13 14:16 UTC, mutotaka0426 commented on test/BonusBlockCarrierTest.cpp
> +    Controller controller;
これも
```suggestion
```

2022-07-14 06:53 UTC, mutotaka0426 approved these changes

2022-07-14 06:53 UTC, merged