close #36 resetMotor()の削除
KatLab-MiyazakiUniv/etrobocon2022 pull request #52
Opened 2022-07-11 01:04 UTC by KakinokiKanta

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- resetMotor()を削除
- resetMotor()を使用しない処理に変更

# 動作テスト
シミュレータ環境と実機で動作が変わらないことを確認

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2022-07-11 08:45 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-07-11 09:17 UTC, miyashita64 approved these changes
LGTM!!

2022-07-11 09:33 UTC, mutotaka0426 requested changes
変更箇所については大丈夫だと思う

あとControllerからresetMotor()を削除しておいて
使わないならそもそもないほうがいいと思う

2022-07-11 15:24 UTC, mutotaka0426 commented
これ @sugaken0528 に一番見てほしいな
ちょっとだけマージまってよ

2022-07-12 02:13 UTC, sugaken0528 approved these changes
LGTM

2022-07-12 02:13 UTC, merged