add:ゲーム動作の親クラスを追加
KatLab-MiyazakiUniv/etrobocon2022 pull request #60
Opened 2022-07-15 08:14 UTC by kodama0720

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- GameMotionクラスの追加

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2022-07-20 11:20 UTC, miyashita64 requested changes
処理はいいと思います。
細かい修正をお願いします。

2022-07-20 11:20 UTC, miyashita64 commented on module/GameMotion/GameMotion.cpp
> + * @brief ビンゴ動作の親クラス
```suggestion
 * @file GameMotion.cpp
 * @brief ゲーム動作の親クラス
```
修正漏れです

2022-07-20 11:20 UTC, miyashita64 commented on module/GameMotion/GameMotion.h
> + * @brief ビンゴ動作の親クラス
```suggestion
 * @file GameMotion.h
 * @brief ゲーム動作の親クラス
```
修正洩れです。

2022-07-20 11:20 UTC, miyashita64 commented on module/GameMotion/GameMotion.h
> +#define BINGO_MOTION_H
```suggestion
#ifndef GAME_MOTION_H
#define GAME_MOTION_H
```
修正洩れです。

2022-07-20 11:20 UTC, miyashita64 commented on test/dummy/GameMotionChild.cpp
> + * @brief GameMotionの子クラス
```suggestion
 * @brief GameMotionの子クラス（ダミー）
```
他のダミークラスでは明記されているので合わせた方がいいと思います。

2022-07-20 11:20 UTC, miyashita64 commented on test/dummy/GameMotionChild.h
> + * @brief GameMotionの子クラス
```suggestion
 * @brief GameMotionの子クラス（ダミー）
```
同上

2022-07-20 12:22 UTC, Takahiro55555 reviewed
@miyashita64 が指摘した点以外は大丈夫だと思います。

2022-07-20 12:23 UTC, Takahiro55555 approved these changes

2022-07-20 17:14 UTC, mutotaka0426 requested changes
テストコードについては考えてなかったけど，確かにこのテストは大事だし良いと思います！

少しだけ気になったところがあったので対応お願いします

2022-07-20 17:14 UTC, mutotaka0426 commented on module/GameMotion/GameMotion.h
> +  GameMotion(double time = 0, double risk = 0);
デフォルト値を設定しない方が，派生先で値を設定し忘れることを予防できませんか？
```suggestion
  GameMotion(double time, double risk);
```

2022-07-20 17:14 UTC, mutotaka0426 commented on test/dummy/GameMotionChild.h
> +  void run(void){};
折角だったら，何か適当にいくつかの汎用動作呼び出したらどうですか？
オーバーライドが正しくできてるテストになるし

2022-07-21 17:43 UTC, mutotaka0426 commented on test/dummy/GameMotionChild.cpp
> +  StraightRunner straightRunner;
汎用動作のインスタンス（LineTracer, StraightRunner, Rotation, etc...）は親クラスが持ってた方がいいかも？

これらの汎用動作インスタンスを使って子クラスが実装します～的な意味で親クラスが持った方がいいかもって思うんだけどどうかな？

2022-07-24 06:32 UTC, kodama0720 commented on test/dummy/GameMotionChild.cpp
> +  StraightRunner straightRunner;
LineTracerはインスタンス化するときにエッジを渡すので、エッジを切り替えて攻略するならLineTracerインスタンスを親クラスが持つのは良くないと思います

2022-07-24 07:36 UTC, mutotaka0426 commented on test/dummy/GameMotionChild.cpp
> +  StraightRunner straightRunner;
LineTracerにエッジ切り替えの処理があるよ？

2022-07-24 07:50 UTC, mutotaka0426 commented on test/dummy/GameMotionChild.cpp
> +  StraightRunner straightRunner;
ちがうな
LineTracerのisLeftEdge，もしくはLineTracerそのものを全体で共有しておかないといけないのか

ゲーム動作をインスタンス化するときにLineTracerインスタンスを参照渡ししておかないといけない？

2022-07-26 09:09 UTC, mutotaka0426 commented
話し合て決まったことを以下にまとめておきます．

EtRobocon2022.cppで`isLeftEdge`を作成して，それをLineTraceAreaやGameAreaで共有する
つまりやることとしては，
- EtRobocon2022.cppで`isLeftEdge`を作成する処理を追加する
- LineTraceArea::run()に引数として`isLeftEdge`の参照を渡す
- GameArea::run()に引数として`isLeftEdge`の参照を渡す
- LineTraceArea::run()とGameArea::run()の中で使用している`isLeftEdge`は全て引数として渡されたものを使う（`isLeftEdge`の変数宣言を削除する）
- LineTracerクラスのコンストラクタで渡す`_isLeftEdge`を参照にする
- LineTracerクラスのメンバ変数`isLeftEdge`を参照にする
- GameMotionのコンストラクタで`isLeftEdge`の参照を受け取り，これを使ってLineTracerインスタンスを初期化する

ようは，`isLeftEdge`を保持する際は全て参照渡しにして共通化するってことです

2022-07-28 03:02 UTC, mutotaka0426 requested changes
いくつか修正があるので対応よろしく

2022-07-28 03:02 UTC, mutotaka0426 commented on test/dummy/GameMotionChild.cpp
> +GameMotionChild::GameMotionChild() : GameMotion(edge, 1.23, 1.09) {}
こうだと思う
```suggestion
GameMotionChild::GameMotionChild(bool& isLeftEdge) : GameMotion(isLfetEdge, 1.23, 1.09) {}
```

2022-07-28 03:02 UTC, mutotaka0426 commented on test/dummy/GameMotionChild.cpp
> +void GameMotionChild::run(bool& isLeftEdge)
ミス？
```suggestion
void GameMotionChild::run()
```

2022-07-28 03:02 UTC, mutotaka0426 commented on test/dummy/GameMotionChild.h
> +  bool edge = true;
いらないかな？

2022-07-28 03:03 UTC, mutotaka0426 commented on module/GameMotion/GameMotion.h
> +
```suggestion
LineTracer lineTracer;
```

2022-07-28 03:25 UTC, kodama0720 commented on module/LineTraceArea.h
> +                               const int targetBrightness);
コースの判別も最初のエッジで行うということですか？

2022-07-28 03:26 UTC, mutotaka0426 commented on module/LineTraceArea.h
> +                               const int targetBrightness);
判別する必要ある？
GameAreaと同じじゃない？

2022-07-28 03:28 UTC, kodama0720 commented on module/LineTraceArea.h
> +                               const int targetBrightness);
LとRで戦略を変えるなら必要だと思います

2022-07-28 03:31 UTC, mutotaka0426 commented on module/LineTraceArea.h
> +                               const int targetBrightness);
なるほど
じゃあGameAreaの方がisLeftCourseが必要？
現状では使ってないけど，多分GameAreaもLRで切り替えるよね？

2022-07-28 03:34 UTC, kodama0720 commented on module/LineTraceArea.h
> +                               const int targetBrightness);
そうですね
追加しておきます

2022-07-28 10:25 UTC, miyashita64 approved these changes
LGTM!!

2022-07-28 11:15 UTC, mutotaka0426 approved these changes
お疲れ様です！
![LGTM](https://image.lgtmoon.dev/175556)

2022-07-28 11:15 UTC, merged