Ticket 56
KatLab-MiyazakiUniv/etrobocon2022 pull request #62
Opened 2022-07-19 13:40 UTC by kawanoichi

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- GameAreaクラスを作成
- LineTraceAreaクラスのゴールゲートから進入サークルまでの処理をBonusBlockCarrierクラスに移動
- パラメータ調整

## 実験方法
コースを10回走らせて精度を確かめた。
※今回はブロックが紙の重なり部分で引っかかり進むことができなかったため、紙の重なり部分の手前までの動作の精度を検証した

## 実験結果
 精度は70パーセントだった。
以下内訳
- 成功 7回
- 途中で止まって失敗　2回
- 他のブロックに当たって失敗　1回

以下、実験時の動画を示す。
- 成功例

- 失敗例1(途中で止まって失敗)

- 失敗例2(他のブロックに当たった失敗)

以下に動画で示す。
## 添付資料

2022-07-20 10:42 UTC, mutotaka0426 requested changes
runToColorのテストコードも書いてほしい
LineTracerを参考にすれば簡単だと思う

2022-07-20 10:42 UTC, mutotaka0426 commented on module/LineTraceArea.h
>    // 以下の2つの定数はファイル読み込みに置き換える（最後の要素は緑までライントレースのパラメータ）
TODOにしておいて
```suggestion
  // TODO: 以下の2つの定数はファイル読み込みに置き換える
```

2022-07-20 10:42 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +    // 白黒以外の色を検出した場合、直進終了
```suggestion
    // 指定された色を検出した場合、直進終了
```

2022-07-20 10:42 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +  if(pwm == 0) return;
他の関数と同様にwarning処理をしてほしい

2022-07-20 10:42 UTC, mutotaka0426 commented on module/Motion/StraightRunner.h
> +  void runStraightToColor(int pwm, COLOR targetColor);
他の関数と同様にコメントを残してほしい
あと関数名runToColorじゃだめ？

どうでもいいけど，runは目標距離，PWM値って順番で引数指定してるから，同じ流れにしたほうがいいのでは
```suggestion

  /**
   * 指定された色まで直進する関数
   * @param targetColor 目標距離
   * @param pwm PWM値
   */
  void runToColor(COLOR targetColor, int pwm);
```

2022-07-20 10:49 UTC, miyashita64 requested changes
動作はいいと思います

2022-07-20 10:49 UTC, miyashita64 commented on module/EtRobocon2022.cpp
>   */
authorに追加してください

2022-07-20 10:49 UTC, miyashita64 commented on module/GameArea.cpp
> +  lineTracer.run(485 + 0, targetBrightness, 50, PidGain(1.0, 0.8, 0.8));
+0 って必要ですか？

2022-07-20 10:49 UTC, miyashita64 commented on module/Motion/StraightRunner.cpp
> +  int currentLeftMotorCount = 0;
```suggestion
  int currentRightMotorCount = initialRightMotorCount;
  int currentLeftMotorCount = initialLeftMotorCount;
```
の方が意味的にはいいと思います

2022-07-20 10:49 UTC, miyashita64 commented on module/Motion/StraightRunner.h
> +  void runStraightToColor(int pwm, COLOR targetColor);
他の命名と合わせるならrunToColor()だと思います。

2022-07-20 12:13 UTC, Takahiro55555 requested changes
気になる点があったため、コメントしました。
ご回答いただけると幸いです。

2022-07-20 12:13 UTC, Takahiro55555 commented on module/Motion/StraightRunner.cpp
> +          = currentDistance / SECTION_DISTANCE * ACCELE_PWM + ACCELE_PWM * ((pwm > 0) ? 1 : -1);
PWM値を徐々に目標値に合わせる処理ですが２つほど、気になる点があります。

- `currentDistance`が`runのStraightToColor`関数が呼ばれてから走った距離ではなく、走行体スタート時からの距離になっていると思われる点
    - ゲームが進行するにつれて加速度が大きくなってしまう?
      -> 解決方針: ループに入る前に、`initialDistance`変数等を用意し関数内での初期値を保持する
- `currentPwm`の値が、時間ではなく進んだ距離によって設定される点
    - バッテリー等の機体の状態によって、最初のループで1mmも動かなかった場合、永遠に動かなくなってしまう?  
      -> 解決方針: ループカウンター又は経過時間等も加味して`currentPwm`の値を設定する

もしも修正が必要な場合は、上部にある`StraightRunner::run`関数が参考になると思います。

そして、自分の理解が間違っていた場合はすみません...

2022-07-21 16:47 UTC, kawanoichi commented
コメントいただいた部分はすべて修正しました。
再びレビューお願いします。
実機を動かした制度は7割成功でした。以下に動画を挙げます。

成功例

https://user-images.githubusercontent.com/96767490/180269119-3853f270-ec44-4f5a-a178-0037ae7269d8.mp4


失敗例１

https://user-images.githubusercontent.com/96767490/180269137-9b68c57c-2941-4b9d-abdd-bfc2f4d560c0.mp4


失敗例２

https://user-images.githubusercontent.com/96767490/180269159-0795ff0c-42d9-4d25-8cb8-1a4f6ad5763f.mp4


失敗例３


https://user-images.githubusercontent.com/96767490/180269173-d85f3524-a70a-463f-a1b9-a8ff9fc9f52d.mp4

2022-07-21 17:35 UTC, mutotaka0426 commented on module/Motion/StraightRunner.cpp
> +    logger.logWarning(" The pwm value passed to StraightRunner::run is 0 ");
関数名間違い
```suggestion
    logger.logWarning(" The pwm value passed to StraightRunner::runToColor is 0 ");
```

2022-07-22 02:33 UTC, Takahiro55555 requested changes
全体の処理の流れは大丈夫だと思います。

以下、コメントした部分に関してです。
- `module/EtRobocon2022.cpp`の修正をお願いします。
- `module/Motion/StraightRunner.cpp`の採否はお任せします。

2022-07-22 02:33 UTC, Takahiro55555 commented on module/Motion/StraightRunner.cpp
> +  // pwm値が0の場合はwarningを出して終了する
`pwm`が`MIN_PWM`(静止時から走行体がモーターを動かせないPWM値)未満の場合も、`warning`を出したほうが良いかもしれません（`pwm`が0でないなら、終了はしなくてもいいかも???）

2022-07-22 02:33 UTC, Takahiro55555 commented on module/Motion/StraightRunner.cpp
> +  int adjustment = 0;           // 左右の誤差の補正値
`Pwm`を付けたほうが分かりやすいかもしれません。
```suggestion
  int adjustmentPwm = 0;        // 左右の誤差の補正値
```

2022-07-22 09:47 UTC, Takahiro55555 approved these changes
LGTM!

お疲れさまです!!!

2022-07-22 10:46 UTC, miyashita64 submitted a review, later dismissed

2022-07-22 11:03 UTC, mutotaka0426 approved these changes
お疲れ様です！
![LGTM](https://image.lgtmoon.dev/174862)

2022-07-22 11:11 UTC, kodama0720 requested changes

2022-07-22 11:11 UTC, kodama0720 commented on module/Motion/StraightRunner.cpp
> +      // 調整距離毎にPWM値を加速値分だけ上げていく
調整距離毎とは？

2022-07-22 11:11 UTC, kodama0720 commented on module/Motion/BonusBlockCarrier.cpp
> +  controller.sleep(100000);
0.1秒?

2022-07-22 11:23 UTC, kodama0720 approved these changes
LGTM!

2022-07-22 11:24 UTC, merged