update : ライントレースエリアの調整
KatLab-MiyazakiUniv/etrobocon2022 pull request #72
Opened 2022-08-02 07:20 UTC by sugaken0528

# チェックリスト
- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- 試走会用のコードから区間毎のsleep無しでライントレースエリアを完走できるようにパラメータを調整
- パラメータの変更によってなぜかrunToColorのテストが通らなくなったので応急処置.具体的には、乱数を用いて色を指定しているが必ず最初に緑が出てくるようになっていたため全く進まずにテストを失敗していた.そのため、乱数の値をずらすことでとりあえず対応.今後どうするかはミーティングで話し合う.

# 動作テスト
- 試走会で走ったコード(区間毎のsleep有り)を研究室のコースで走らせた
  - 試走会での走行率2/2
  - 研究室での走行率4/5
 
 ライントレースエリアにおいては研究室と試走会ではあまり差がないと感じる.

- 区間ごとのsleep無しで走るようにパラメータを調整後、20回研究室のコースで試走
   - 走行体1: 成功率95%(19/20) 平均タイム13.9145s
   - 走行体2: 成功率60%(12/20) 平均タイム12.06s

## 添付資料

- 試走会のコースを走行

https://user-images.githubusercontent.com/62526141/182309502-d17ca2e9-9891-46c8-b235-905674c240e8.MOV

- 試走会で走らせたコードで研究室のコースを走行

https://user-images.githubusercontent.com/62526141/182309599-b3f372e2-4351-434e-b398-4987a1bdcae0.MOV

- 今回の調整後の成功例(走行体1)

https://user-images.githubusercontent.com/62526141/182310168-dc742cbc-a112-436e-865c-9ff4d96304d0.MOV

- 今回の調整後の失敗例(走行体1)

https://user-images.githubusercontent.com/62526141/182310485-fa37f421-3121-49ca-9e05-c4a992a7c440.MOV

- 今回の調整後の成功例(走行体2)

https://user-images.githubusercontent.com/62526141/182310651-a21cc9e6-6b3d-4028-8125-7c04908c205d.mov

- 今回の調整後の失敗例(走行体2)

https://user-images.githubusercontent.com/62526141/182315061-60eadc3d-11ab-4050-894a-2b68dd613dfa.MOV

2022-08-02 08:18 UTC, mutotaka0426 commented
> * パラメータの変更によってなぜかrunToColorのテストが通らなくなったので応急処置.具体的には、乱数を用いて色を指定しているが必ず最初に緑が出てくるようになっていたため全く進まずにテストを失敗していた.そのため、乱数の値をずらすことでとりあえず対応.今後どうするかはミーティングで話し合う.

乱数の値が同じになるって問題は取り合えず後で考えるとして，色は乱数で決定するなら，runToColorのテストの方を変えるべきだと思う．
今のアサーションが`expected<actual`になってるけど，`expected<=actual`であるべきじゃない？もともと，乱数で決めるならいきなり色を認識する可能性はあるし．

2022-08-03 13:15 UTC, kodama0720 approved these changes
LGTM!
プルリクのタイトルだけ修正お願いします。

2022-08-03 16:00 UTC, miyashita64 approved these changes
LGTM!

テストに関して、必要かはミーティングで話し合うとして、テストする場合はsrand()で定数を指定すれば安定してテストができる気がしました。

2022-08-03 20:49 UTC, mutotaka0426 commented
> テストに関して、必要かはミーティングで話し合うとして、テストする場合はsrand()で定数を指定すれば安定してテストができる気がしました。

srand()知らなかった
rand()だけだと乱数シード？ってのが同じになるんだね

ならrand()呼び出す前に` srand((unsigned int)time(NULL));`を呼び出せ場良い感じかな？
俺はテストは絶対必要だと思うから，srand処理を追加してほしいかな

参考: [C言語 乱数の生成【randとsrandを使ったサンプルコード】](https://monozukuri-c.com/langc-funclist-rand/)

2022-08-03 20:57 UTC, mutotaka0426 requested changes
コメントの修正だけ

あと，ダミーのカラーセンサがすぐに色を認識した場合の対応をするなら，同様のテストがLineTracerTestにもあるはずだから，そっちも変更してほしい

2022-08-03 20:57 UTC, mutotaka0426 commented on test/StraightRunnerTest.cpp
> +    EXPECT_LE(expected, actual);  // 初期値より少しでも進んでいる
コメントが適切じゃないかな
```suggestion
    EXPECT_LE(expected, actual);  // 初期値より0cm以上進んでいる
```

2022-08-03 22:27 UTC, Takahiro55555 approved these changes
@mutotaka0426 が指摘している点以外は問題ないと思います

LGTM!!!

2022-08-04 06:28 UTC, mutotaka0426 commented on test/LineTracerTest.cpp
> +    EXPECT_LT(expected, actual);  // 初期値より0cm以上進んでいる
```suggestion
    EXPECT_LE(expected, actual);  // 初期値より0cm以上進んでいる
```

2022-08-04 06:35 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/113850)

2022-08-04 06:36 UTC, merged