close #71 ライントレースのパラメータをファイルから読み込む
KatLab-MiyazakiUniv/etrobocon2022 pull request #75
Opened 2022-08-02 14:24 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- LineTraceAreaクラスにファイル読み込みで走行パラメータ(走行距離、PWM値、PIDゲイン)を取得する処理を追加
- プロジェクトルートにdatafiles/を設置
- datafiles/にLとRコース用のパラメータファイルを設置(走行距離,PWM値,Pゲイン,Iゲイン,Dゲイン,コメント)

# 動作テスト

## 実験方法
パラメータファイルを編集し、コンパイルせずに実行した際に挙動が変わることを確認する。

## 実験データ

編集前のパラメータ：すべての直進でpwm=50, すべてのカーブでpwm=30
```
1100,50,0.2,0.8,0.1,直進
312,30,1.0,0.7,0.2,カーブ
1730,50,0.3,0.8,0.08,直進
350,30,1.0,0.9,1.0,カーブ
790,50,0.3,0.7,0.08,直進
```

編集後のパラメータ：最初にpwm=100で少し直進, それ以外は編集前と同様
```
300,100,0.1,0.08,0.001,直進
800,50,0.2,0.8,0.1,直進
312,30,1.0,0.7,0.2,カーブ
1730,50,0.3,0.8,0.08,直進
350,30,1.0,0.9,1.0,カーブ
790,50,0.3,0.7,0.08,直進
```

## 実験結果
編集後のみ、スタート時に急加速した。

## 添付資料

2022-08-02 14:55 UTC, mutotaka0426 requested changes
ごめん，まだ途中なのかもしれないけど，パッと見て気になったからとりあえず書きました

2022-08-02 14:55 UTC, mutotaka0426 commented on module/LineTraceArea.cpp
> +    lineTracer.run(params[i].distance, targetBrightness, params[i].pwm, params[i].pidGain);
ここ区間距離は 計測距離 + 調整距離 をイメージしてたんだけどまとめる？
計測距離は定数としてこのクラスが持ってた方がいいのかなって思ったけどまとめた方がいい？
これはみんなの意見を聞きたいところでもあるけど
もしくは何か理由があってくっつけてる？
```suggestion
    lineTracer.run(DISTANCE[i] + params[i].tweak, targetBrightness, params[i].pwm, params[i].pidGain);
```

2022-08-03 03:19 UTC, miyashita64 commented on module/LineTraceArea.cpp
> +    lineTracer.run(params[i].distance, targetBrightness, params[i].pwm, params[i].pidGain);
クラスで持つと、区間数を変えたい場合にクラス内の定数を変える必要が出てくるので、どちらも外部ファイルでできた方がいいと思いました。
比較的みづらいcsvファイルで区間の長さと調整距離をファイル等に分けるのもどうかと思いまとめました。

2022-08-03 20:42 UTC, mutotaka0426 requested changes
動いてるみたいだし，ほぼ問題ないと思う
小さいところだけ指摘してるので対応お願いします

あと手が空いたらでいいけど，vectorの件はslackにバグレポート書いてほしいです

2022-08-03 20:42 UTC, mutotaka0426 commented on module/LineTraceArea.h
>  #include <string>
`<string.h>`を読み込んでるから`<string>`は多分いらないね
```suggestion
```

2022-08-03 22:34 UTC, Takahiro55555 approved these changes
@mutotaka0426 の指摘している点以外は大丈夫だと思います。

LGTM

2022-08-04 05:47 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/105180)

2022-08-04 06:30 UTC, kodama0720 approved these changes
LGTM!

2022-08-04 06:47 UTC, merged