アームを一定の角度に保つタスクを追加
KatLab-MiyazakiUniv/etrobocon2022 pull request #84
Opened 2022-08-11 06:30 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- app.cfgにアームを一定に保つタスクを追加
- app.h, app.cpp にアーム一定に保つ処理を追加

# 動作テスト

## 実験方法
メインタスクに関わらず、アームを一定に保っているか確認する。

## 実験データ
後日、動画を添付

## 実験結果
アームが指定した角度に動くことを確認した。

## 添付資料
[タスク設計の参考にしたetrobcon2021のコード](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/pull/106)
[後輩たちのためのEV3rt講座⑧(タスク・周期ハンドラ)](https://qiita.com/koushiro/items/22a10c7dd451291fd95b)

2022-08-15 08:46 UTC, kodama0720 reviewed
処理は良いと思います。
できればアームの角度を保っている動画が欲しいです。

2022-08-16 19:28 UTC, Takahiro55555 requested changes
Issueには、実現方法に
>PID制御で指定した角度に調整するタスクを追加する

とありましたが、PID制御を用いていない理由等を書いていただけると幸いです（使わなくても十分動く？）。


また、少し気になったのですが、
>RasPikeの充電状態によって、モータの出力が変わる？pwmが10で動いた機体が15でやっと動くようになっていて、RasPike充電後は10でも高速に動いた。

とあるのですが、「RasPikeの充電状態」モバイルバッテリの残量のことを指しているのでしょうか？
それとも、SPIKE本体のバッテリのことを指しているのでしょうか？

2022-08-16 19:28 UTC, Takahiro55555 commented on app.cpp
> +  }
`app.cpp`に実際の処理を記述するのは、関数を呼び出すだけのメインタスク部分と方針が異なるため、個人的には違和感があります。
[昨年のコード](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/blob/main/app.cpp)では、`app.cpp`に直接処理を記述していないようなので、処理を記述するのは別ファイルにしたほうが良いかもしれません。

2022-08-17 02:40 UTC, miyashita64 commented
> PID制御を用いていない理由等を書いていただけると幸いです（使わなくても十分動く？）。

PID制御だと、すでに目標値に達している（P値が0）場合でも、I値やD値で余計な補正が入りモータに不要な負荷がかかる恐れがあると考えPID制御をやめました。他の理由としては、ほとんどの場合、一度の補正でアームは下がるのでPID制御の恩恵があまり得られない、また、起動時のアームの角度が回転量0に設定され、目標値の指定が難しいからです。


>「RasPikeの充電状態」モバイルバッテリの残量のことを指しているのでしょうか？
> それとも、SPIKE本体のバッテリのことを指しているのでしょうか？

SPIKE本体のことです。直接ケーブルから充電されていたSPIKEを使ったところ、以前動作させたときと比べ目に見えて出力が強くなっていました。

2022-08-17 09:53 UTC, miyashita64 commented on app.cpp
> +  int prevCount = currentCount - 1;
本関数では、補正によってアームが目的の方向に移動したかどうかを`currentCount > prevCount`の比較で判定しています。
```
// アームが下がる(回転量が大きくなる)余地があれば調整する
pwm = (currentCount > prevCount || maxCount > currentCount) ? MIN_PWM : 0;
```

この処理を通すために、`prevCount`を`currentCount`より確実に小さい値で初期化しています。

2022-08-17 09:59 UTC, Takahiro55555 approved these changes
LGTM!!!

お疲れ様です!!!

2022-08-17 10:25 UTC, kawanoichi commented
![LGTM](https://user-images.githubusercontent.com/96767490/185096433-660d5cc4-38e0-4b44-9c5d-f6bce55c40b4.jpg)

2022-08-17 10:25 UTC, miyashita64 commented
機体や充電状態によって動かない場合があるようなのでPWM値を上げました

2022-08-17 10:28 UTC, kawanoichi approved these changes
![177684](https://user-images.githubusercontent.com/96767490/185097032-73a6f508-69c3-458b-b546-5ab45ae8cb45.jpg)

2022-08-17 13:51 UTC, mutotaka0426 approved these changes
お疲れ様！
![LGTM](https://image.lgtmoon.dev/177697)

2022-08-17 22:12 UTC, sugaken0528 approved these changes
LGTM

2022-08-18 04:33 UTC, merged