close #80 ライントレースの調整(走行体1)
KatLab-MiyazakiUniv/etrobocon2022 pull request #86
Opened 2022-08-14 13:43 UTC by kodama0720

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
- ライントレースのパラメータ変更
- 走行体2はしばしお待ちください

# 動作テスト

## 実験方法
ライントレースエリアを20回走行し、成功率とタイムを計測した。

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果
成功：　12
第1カーブ失敗：　3
第2カーブ失敗：　5

成功率：　6割
平均タイム：　10.7秒

## 添付資料
- 成功

https://user-images.githubusercontent.com/83354922/184539765-be3d3aa7-b49b-4c69-a418-5eabf656741b.MOV

- 失敗（第1カーブ）

https://user-images.githubusercontent.com/83354922/184539815-53159899-1fb7-4a13-9e53-bbd9f5604a3a.MOV

- 失敗（第2カーブ）

https://user-images.githubusercontent.com/83354922/184539756-d09ddd5d-d7f1-4446-8489-ab21ea268496.MOV

2022-08-15 20:53 UTC, mutotaka0426 requested changes
走行体2の方と競合してしまうから，`LineTraceLeftParams.csv`じゃなくて，走行体番号と調整日を名前にしたファイルにしてほしい
具体的には[ticket-79](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/pull/87)に合わせて，`Left_01_0815.csv`かな
調整者の名前があってもいいかもしれないけど，そこは@sugaken0528 と合わせてくれればいい

`LineTraceLeftParams.csv`の方の変更はないようにして，新たに`Left_01_0815.csv`を作る形にしてほしい

2022-08-15 21:37 UTC, mutotaka0426 commented
[ticket-79](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/pull/87)の方でも指摘したけど，チケットの完了条件を満たしていないなら，どの部分をなぜ妥協したのかとかを書いてほしい

あと，使わないなら実験データの項目消していいよ

2022-09-21 06:39 UTC, mutotaka0426 approved these changes
LGTM!

内容とは関係ないただの提案なんだけど，こういう退避してたりするファイル系は`datafiles/`内にさらに別のフォルダ作って置いておくとかダメかな？
`datafiles/`内をパッと見たときに見づらいなって感じたんだけど，どうかな？

2022-09-22 07:49 UTC, kawanoichi approved these changes
![78285](https://user-images.githubusercontent.com/96767490/191688966-537aa308-0075-4dcd-b6b5-4d9e0b9580ab.jpg)

2022-09-26 08:59 UTC, KakinokiKanta approved these changes
LGTM!!

2022-09-26 09:00 UTC, merged