close #73, close #82, close #83 動作をCommandパターンに作り直す
KatLab-MiyazakiUniv/etrobocon2022 pull request #88
Opened 2022-08-14 21:30 UTC by mutotaka0426

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- 動作系の関数をそれぞれCommandパターンとして作り直した
- 動作コマンド記述したファイルを解析してCommandのインスタンスを生成する，`MotionParser`クラスを追加
- LineTraceArea及びGameAreaを，動作コマンドを読み込んで攻略するように修正
- 動作コマンドは以下の8種
  - LD : 指定距離ライントレース
  - LC : 指定色までライントレース
  - SD : 指定距離直進
  - SC : 指定色まで直進
  - RT : 回頭
  - TD : 指定距離旋回
  - EC : エッジ切り替え
  - SL : タスクスリープ
- GameMotionパッケージを削除
- ColorJudgeクラスとMileageクラス，Pidクラスを，新たに作成した`Calculator`パッケージに移動
- コマンド読み込みのテスト用に，テストのスクリプトを修正

# 動作テスト
Commandパターンに変更する前と同様に走行体が動作していることを確認した．
動作確認の動画を以下に示す．
なお，ライントレースエリア攻略のパラメータは[ticket-79](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/pull/87)で調整されたものを使用している．

https://user-images.githubusercontent.com/56989154/184555584-aa2e99c2-c4f8-4b64-9db1-e59d531e6c8c.MOV

2022-08-16 04:27 UTC, kodama0720 requested changes
実装お疲れ様です。
確認した範囲で気になった点を挙げます。

2022-08-16 04:27 UTC, kodama0720 commented on module/MotionParser.cpp
> +    } else if(command == COMMAND::SD) {  // 距離指定極真動作の生成
指定距離直進動作？

2022-08-16 04:29 UTC, kodama0720 reviewed
NoneMotionって必要ですか？

2022-08-16 17:34 UTC, miyashita64 requested changes
ほとんど問題ないと思います。

個人的には、〇〇erDistance, 〇〇erColorという名前よりdistance〇〇ing, color〇〇ingの方が動作っぽいと感じます。とはいえ、今までの間数名から理解はできるので他に気になる人がいなければ、このままでいいと思います。

コメントで少し気になったので修正をお願いします。

2022-08-16 17:34 UTC, miyashita64 commented on module/Motion/LineTracerDistance.h
> +   * @param _targetBrightness 目標輝度
targetDistanceが0の場合にはwarningを出して終了するので、`目標距離 0~∞`は不適切だと思います。∞にも違和感があるので`正の数`とかでどうでしょう？
また、目標輝度も0~100の範囲にあるはずなので、書いた方がいいと思います。

2022-08-16 17:34 UTC, miyashita64 commented on module/Motion/LineTracerDistance.h
> +  double targetBrightness;  // 目標輝度
同上

2022-08-16 17:34 UTC, miyashita64 commented on module/Motion/StraightRunnerDistance.h
> +   * @param _targetDistance 目標距離 0~∞
同上

2022-08-16 17:34 UTC, miyashita64 commented on module/Motion/StraightRunnerDistance.h
> +  double targetDistance;              // 目標距離 0~∞
同上

2022-08-16 19:50 UTC, Takahiro55555 commented on test/gtest/gtest_build.sh
> +cp ../datafiles/* etrobocon2022/datafiles/
「疑似的な」ものではない気がする!?
```suggestion
# NOTE: 実行とテストでカレントディレクトリが異なり，テストの際にファイルパスの指定ができないため，テスト用にdatafiles/ディレクトリを作成・コピーする
mkdir -p build/etrobocon2022/datafiles
cp datafiles/* build/etrobocon2022/datafiles/
cd build
```

2022-08-16 21:04 UTC, sugaken0528 requested changes
テストコードまだ見れてないけどそれ以外はOKだと思います

2022-08-17 02:43 UTC, Takahiro55555 requested changes
全体的に読みやすかったです。
少し気になる点があったため、コメントしました。

2022-08-17 02:43 UTC, Takahiro55555 commented on test/EdgeChangerTest.cpp
> +    bool isLeftEdge = false;  // run()を実行することでこの変数が切り替わる
参照渡ししていることを書いたほうがより理解度が上がるかも?

```suggestion
    bool isLeftEdge = false;  // run()を実行することでこの変数が切り替わる(コンストラクタで参照渡しをするため)
```

2022-08-17 02:43 UTC, Takahiro55555 commented on test/GameAreaTest.cpp
> +    EXPECT_EQ(expected, actual);  // WarningやErrorが出ていないかテスト
`EXPECT_TRUE`というものが使えるようです([参考資料](http://opencv.jp/googletestdocs/primer.html#primer-basic-assertions))。
```suggestion
    // find("str")はstrが見つからない場合string::nposを返す
    bool actual = output.find("Warning") == string::npos && output.find("Error") == string::npos;

    EXPECT_TRUE(actual);  // WarningやErrorが出ていないかテスト
```

2022-08-17 02:43 UTC, Takahiro55555 commented on test/GameAreaTest.cpp
> +    EXPECT_EQ(expected, actual);  // WarningやErrorが出ていないかテスト
同上
```suggestion
    // find("str")はstrが見つからない場合string::nposを返す
    bool actual = output.find("Warning") == string::npos && output.find("Error") == string::npos;

    EXPECT_TRUE(actual);  // WarningやErrorが出ていないかテスト
```

2022-08-17 02:43 UTC, Takahiro55555 commented on test/LineTraceAreaTest.cpp
> +    EXPECT_EQ(expected, actual);  // WarningやErrorが出ていないかテスト
同上
```suggestion
    // find("str")はstrが見つからない場合string::nposを返す
    bool actual = output.find("Warning") == string::npos && output.find("Error") == string::npos;

    EXPECT_TRUE(actual);  // WarningやErrorが出ていないかテスト
```

2022-08-17 02:43 UTC, Takahiro55555 commented on test/LineTraceAreaTest.cpp
> +    EXPECT_EQ(expected, actual);  // WarningやErrorが出ていないかテスト
同上
```suggestion
    // find("str")はstrが見つからない場合string::nposを返す
    bool actual = output.find("Warning") == string::npos && output.find("Error") == string::npos;

    EXPECT_TRUE(actual);  // WarningやErrorが出ていないかテスト
```

2022-08-17 09:05 UTC, mutotaka0426 commented on datafiles/ToEndPointLeft.csv
> +LC,RED,0,40,0.1,0.08,0.08,赤（端点サークル）までライントレース
end pointじゃなくてもいいんだけど，カメラシステムの[camera_coordinate_calibrator.py](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/blob/main/camera_system/camera_coordinate_calibrator.py)でもend pointにしてるから，そっちも変える必要が出ると思う

2022-08-17 09:27 UTC, mutotaka0426 commented on module/EtRobocon2022.cpp
> +  // スタートのメッセージ
出力とは限らないから（現状は出力だけど）`メッセージログを出す`にします

2022-08-17 09:41 UTC, mutotaka0426 commented on module/MotionParser.cpp
> +  while(fgets(row, BUF_SIZE, fp) != NULL) {
コメントは読み込まれなくても大丈夫だけど，怖いからBUF_SIZEは大きくします

2022-08-17 14:46 UTC, miyashita64 approved these changes
LGTM!!お疲れ様です！

2022-08-17 21:38 UTC, sugaken0528 commented on datafiles/ToEndPointLeft.csv
> +LC,RED,0,40,0.1,0.08,0.08,赤（端点サークル）までライントレース
まあ意味的にはそのままなんでこのチケット外の作業になるならそこまでして変えなくて大丈夫と思うます

2022-08-17 21:40 UTC, sugaken0528 requested changes
コメントの修正漏れ

2022-08-17 21:40 UTC, sugaken0528 commented on test/MotionTest.cpp
> +    char expected[BUF_SIZE];  // log用にメッセージを一時保存する
```suggestion
    char expected[BUF_SIZE];  // log用にメッセージを一時保存する領域
```

2022-08-17 21:40 UTC, sugaken0528 commented on test/dummy/MotionChild.cpp
> +  char buf[BUF_SIZE];  // log用にメッセージを一時保存する
```suggestion
  char buf[BUF_SIZE];  // log用にメッセージを一時保存する領域
```

2022-08-18 01:04 UTC, Takahiro55555 requested changes
テストコードも、できれば`snprintf`で統一したほうが良いと思いました（プロジェクト全体でもコメントした2ヶ所のみが`sprintf`だったため）。

2022-08-18 01:04 UTC, Takahiro55555 commented on test/MotionTest.cpp
> +    sprintf(expected, "Run MotionChild (targetDistance: %.2f, pwm: %d)\n", targetDistance, pwm);
一応、こちらも`snprintf`で統一したほうが良いかも?
```suggestion
    sprintf(expected, BUF_SIZE, "Run MotionChild (targetDistance: %.2f, pwm: %d)\n", targetDistance, pwm);
```

2022-08-18 01:04 UTC, Takahiro55555 commented on test/dummy/MotionChild.cpp
> +  sprintf(buf, "Run MotionChild (targetDistance: %.2f, pwm: %d)", targetDistance, pwm);
同上
```suggestion
  sprintf(buf, BUF_SIZE, "Run MotionChild (targetDistance: %.2f, pwm: %d)", targetDistance, pwm);
```

2022-08-18 04:33 UTC, Takahiro55555 approved these changes
LGTM

お疲れ様です!!!

2022-08-18 04:34 UTC, sugaken0528 approved these changes
LGTM

2022-08-18 04:43 UTC, kodama0720 approved these changes
LGTM!

2022-08-18 04:48 UTC, merged