Ticket 77
KatLab-MiyazakiUniv/etrobocon2022 pull request #89
Opened 2022-08-15 07:42 UTC by sap2368

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- ゲームエリア内動作のパラメータ調整用コードを追加した
# 動作テスト
- 3ノード間の移動をそれぞれ10回ずつ行った
- 各動作の時間を計測した。動画から推測することは困難だっため、スマートフォンのストップウォッチで計測した。
# 実験結果
成功率：全17動作の内10動作が成功率90%、7動作が100%だった。
動作時間(計測途中※以下は別機体(一号)で本番で使用しないバッテリーを用いたものである)
- 縦調整：0.5
- 斜め調整： 0.6
- 中点→ブロック(ブロック無/有):0.71/1.09
- 中点→交点(ブロック無/有):0.86/1.65
- 中点→中点(ブロック無/有):0.91/1.97
- 交点→中点(ブロック無/有):0.83/1.63
- 交点→ブロック(ブロック無/有):0.75/1.55
- ブロック→交点 (ブロック無/有):0.83/1.41
- ブロック→中点 (ブロック無/有):0.80/1.28
## 添付資料

2022-08-15 21:28 UTC, mutotaka0426 reviewed
折角ちゃんとしたコードを書いてくれてるしマージしてもいいかもね
[ticket-82](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/pull/88)の方でCommandパターンに置き換えてるから，このままだと使えなくはなるけど，残しておいた方が後々調整しやすそう

`module/`下だとコンパイルに影響するから`etrobocon2022/`下とかに調整用コードのディレクトリを置くのとかどうかな？みんなに要相談だけど

2022-08-15 21:28 UTC, mutotaka0426 commented on module/GameMotion/PartsofGameMotion.h
> + * @file PartsofGameMotion.cpp
```suggestion
 * @file PartsofGameMotion.h
```

2022-08-15 21:28 UTC, mutotaka0426 commented on module/GameMotion/PartsofGameMotion.cpp
> + * @file PartsofGameMotion.cpp
こういう時はofも大文字にして大丈夫だよ
```suggestion
 * @file PartsOfGameMotion.cpp
```

2022-08-16 05:17 UTC, kawanoichi commented
実際にどんな動きをしているか見たいので動画も載せてほしいです。

2022-08-17 04:01 UTC, sugaken0528 requested changes
ETrobocon2022/直下に置いとくといいと思います。
同じく動作系のプルリクには動画をお願いしたいです。

2022-08-17 05:14 UTC, sugaken0528 requested changes
縦調整と斜め調整以外の7つのノード間移動の成功率をそれぞれお願いします

2022-08-17 17:10 UTC, KakinokiKanta commented
最新版の各ノード間の動作時間と成功率は以下の通りです。

| 2ノード | 成功率 | 平均動作時間 |
| --- | --- | --- |
| 縦調整 |  | 0.2558 |
| 斜め調整 |  | 0.262 |
| 中点→ブロック置き場 | 10/10 | 0.697 |
| 中点→交点 | 8/10 | 0.556 |
| 中点→中点 | 5/10 | 1.149 |
| 交点→中点 | 8/10 | 0.548 |
| 交点→ブロック置き場 | 10/10 | 0.784 |
| ブロック置き場→中点 | 9/10 | 0.8094 |
| ブロック置き場→交点 | 10/10 | 1.07 |
| 復帰動作 | 10/10 | 2.8 |

2022-08-17 18:34 UTC, KakinokiKanta commented
Uploading IMG_5680.MOV…

2022-08-18 04:38 UTC, KakinokiKanta commented
中点→中点→交点
成功例：

https://user-images.githubusercontent.com/105735727/185294835-823d2986-9253-49b2-a510-1830774415e1.MOV

失敗例：

https://user-images.githubusercontent.com/105735727/185294913-3bf46514-98f9-427e-b920-41f1b3ce95e9.MOV

2022-08-18 04:39 UTC, KakinokiKanta commented
交点→中点→ブロック置き場
成功例：

https://user-images.githubusercontent.com/105735727/185295114-f458c673-9a81-4ca4-a4ad-070bc57defba.MOV

2022-08-18 04:41 UTC, KakinokiKanta commented
交点→ブロック置き場→中点
成功例：

https://user-images.githubusercontent.com/105735727/185295315-6919c290-472d-46b4-89ed-caf5d26ebd3c.MOV

2022-08-18 04:42 UTC, KakinokiKanta commented
ブロック置き場→中点→交点
成功例：

https://user-images.githubusercontent.com/105735727/185295474-6606a975-9df6-4da9-b0a5-e55262317749.MOV

2022-08-18 04:43 UTC, KakinokiKanta commented
ブロック置き場→交点→ブロック置き場
成功例：

https://user-images.githubusercontent.com/105735727/185295583-f28e8b8a-2a19-4ed8-ae67-ca8e0f28b9d7.MOV

2022-08-18 04:44 UTC, KakinokiKanta commented
復帰動作
成功例：

https://user-images.githubusercontent.com/105735727/185295661-bde93dae-0659-4df9-8a37-b112e03a05ce.MOV

2022-08-18 04:57 UTC, KakinokiKanta commented
中点→中点→交点
成功例：

https://user-images.githubusercontent.com/105735727/185297202-d0fe5b32-c120-4a8b-a4a9-f73cb18354c8.MOV

失敗例：

https://user-images.githubusercontent.com/105735727/185297259-d9911245-325e-4d62-9744-3c4022baf9fd.MOV

2022-09-01 06:03 UTC, closed without merging