#8 ローカル環境でgtestを実行できるようにする
KatLab-MiyazakiUniv/etrobocon2022 pull request #9
Opened 2022-06-04 10:39 UTC by miyashita64

# チェックリスト
- [x] ./make.sh でビルドできる
- [x] ./make.sh で
- [x] ./gtest_all.sh でgtestを実行できる

# 変更点
- etrobocon2021リポジトリからMakefile, gtest_all.sh, make.sh, .gitignoreをコピー
- 2021を2022に変更
- test, module, module/API, module/Motionディレクトリを設置
- 不要な記述を削除

# 動作テスト
- ./make.sh でビルドが通ることを確認
- ./make.sh sim up でシミュレータを起動できることを確認
- ./gtest_all.sh でGoogle Testを実施できることを確認(etrobocon2021のテストケースとクラスを使用)

2022-06-04 14:24 UTC, kodama0720 commented on CMakeLists.txt
> +include_directories(${GTEST_INCLUDE_DIRS} ${PROJECT_SOURCE_DIR}/module)
ここに書いてあるディレクトリは存在しなくてもいい？

2022-06-04 14:37 UTC, miyashita64 commented on CMakeLists.txt
> +include_directories(${GTEST_INCLUDE_DIRS} ${PROJECT_SOURCE_DIR}/module)
空のディレクトリとして作ってたんだけど、空だとgitの管理対象から外れるようです。
修正します。

2022-06-05 02:39 UTC, kodama0720 submitted a review, later dismissed
LGTM

2022-06-05 18:21 UTC, Takahiro55555 approved these changes
LGTM!!!
素早いPRありがとうございますm(_ _ )m

### P.S.
実機で動作を確認したところ正常に？動作しました。

#### 確認手順
1. `/home/katlab/work/RasPike/sdk/workspace`でリポジトリをクローン
2. `app.cpp`の`ext_tsk();`が記述されている上の行に、`printf("Hello KatLab\n");`を追記
3. `make img=etrobocon2022; make start`を実行し、`Hello KatLab`が表示されることを確認

2022-06-05 20:16 UTC, Takahiro55555 requested changes
一度Approveしましたが、見逃し？があったため取り消します。
すみません...

ついでに、お手数をおかけしますが[`merge-7_8`ブランチ](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/commits/merge-7_8)を参考に、以下のファイルの修正と追加をしていただければ幸いです。
（プルリクを同時に出してしまうと、マージする順番によっては少し面倒なことになりそう？）

[`merge-7_8`ブランチ](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/commits/merge-7_8)において、実機でのビルド及び実行(make img=etrobocon2022; make start)とGoogleTestが通ることは確認しました。

### 修正（コメント済み）
- `app.cpp`

### 追加
- `module/EtRobocon2022.cpp`
- `module/EtRobocon2022.h`
- `test/EtRobocon2022Test.cpp`

2022-06-05 23:46 UTC, miyashita64 commented on app.cpp
> +  ext_tsk();
ご指摘ありがとうございます。
修正しました。

2022-06-06 05:25 UTC, Takahiro55555 approved these changes
LGTM!!!

2022-06-06 07:12 UTC, kodama0720 submitted a review, later dismissed

2022-06-07 06:30 UTC, mutotaka0426 requested changes
正常に動作してるみたいだし基本的にはokだと思う
あとは小さいところだけ修正をお願いします．

2022-06-07 06:30 UTC, mutotaka0426 commented on module/EtRobocon2022.h
> + * @author Takahiro55555
現時点でこのコードに手を加えた人を載せるべきだから，authorには宮下君のユーザ名をいれた方がいいと思う
直接動作には関係しなくても，ドキュメントとかはしっかりしとかないと後々ぐだるよ

それともここって上田君がやった？

2022-06-07 14:46 UTC, mutotaka0426 approved these changes
LGTM！

2022-06-07 14:50 UTC, Takahiro55555 approved these changes

2022-06-08 06:19 UTC, kodama0720 approved these changes

2022-06-09 05:52 UTC, sugaken0528 approved these changes
LGTM
遅くなってすみません

2022-06-09 05:58 UTC, merged